### ISSUE TITLE
Creating a S&D mission with 2 Escort Aircraft SEAD loads the F18 with Anti-Ship loadout. 

### ISSUE THREAD

**Issue by TinuzzWasTaken** [akaAgar/briefing-room-for-dcs#1]
[test.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5724898/test.zip)

**Comment by john681611** [comment]
#4 fixes

**Comment by akaAgar** [comment]
Fixed. There was a typo in Database/Units/PlaneFighter/FA-18C Hornet.ini, the antiship payload was attributed to the SEAD payload.
