### ISSUE TITLE
AV-8b issue on Nevada

### ISSUE THREAD

**Issue by stevie02** [akaAgar/briefing-room-for-dcs#103]
I’m impressed with the download. However, when I’m on the Nevada map using a briefing room generated mission, my throttle (only fly AV8b) doesn’t work. I always start dark and cold on the ramp but can’t get past the initial engine start to .92 power, moving my throttle forward to inject fuel into engine doesn’t do anything. This only happens on Nevada. Caucuses is fine.

**Comment by john681611** [comment]
Handbrake off? catches me every time.

**Comment by stevie02** [comment]
Thanks, but it’s not that. Also works fine on Syria map.

**Comment by john681611** [comment]
hmm, I don't personally have the Nevada map so I can't test for you, unfortunately.

**Comment by TheJovianFlies** [comment]
Tested and confirmed. Even the auto start procedure fails in Nevada at this point with RPM 0092:

![image](https://user-images.githubusercontent.com/80196497/114321732-f1a23700-9b24-11eb-8e23-4e8e23de8163.png)

Also, if I have the start location on runway in Nevada, the plane shuts off in about 5 seconds.

**Comment by john681611** [comment]
#80

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
