### ISSUE TITLE
A-4E-C issues (liveries and radio)

### ISSUE THREAD

**Issue by jacobs7th** [akaAgar/briefing-room-for-dcs#113]
Hello guys, first of all thanks for the latest release! I was using briefing room to generate an interdiction mission for the A-4E (I'm on latest bate-2 release testing the new A-4E EFM), and I saw some strange issues.

First, the A-4 loads with a default white skin, and with a distorted airframe number on aircraft nose.  The issue happens both for the dcs mission editor, and also on 3d, when you ask for 'rearm / refuel' screen. This behavior happens only for missions generated by BriefingRoom, if I create a new mission using the mission editor, the A-4E skins load correctly.

Lastly, I'm unable to use the radios. This new A-4E beta version has radios working, but when I try to use it on a mission generated by BR, it's not working, the knobs move when I click it, bit the radio frequency doesn't change.

**Comment by john681611** [comment]
I take it this is SP and not MP.

**Comment by john681611** [comment]
Has the aircraft changed its DCS ID?
That or does it have special settings over a default aircraft.

**Comment by jacobs7th** [comment]
Hello John! Yeah, it's singleplayer mission. Latter today I'll test as you proposed. Thanks for your reply. About helping out, I'll see what I can do. I'm a c# developer, but mostly backend/web applications. I don't have experience with windows forms projects. But I can clone the repo and see if I can contribute. ;)

**Comment by john681611** [comment]
Dude same most of the code doesn't need windows forms experience. Join our discord: https://discord.gg/NqUwjh3t

**Comment by john681611** [comment]
This should be fixed now.
