### ISSUE TITLE
CSAR: pilot is not generated

### ISSUE THREAD

**Issue by cirmi00** [akaAgar/briefing-room-for-dcs#116]
Hey mate,

First, huge thanks for the generator, I find it amazing. We just flew a CSAR mission with our group (8 or so people) and almost everything was good, but the downed pilot didn't spawn. After the mission I checked in the mission editor, he was not there either. Then I re-generated the mission a couple times, sometimes he was there, sometimes he wasn't.

The settings we used:
![image](https://user-images.githubusercontent.com/72670020/110389848-65a07980-8065-11eb-90f1-f8c61b1552b1.png)

And the empty target area:
![image](https://user-images.githubusercontent.com/72670020/110389945-8799fc00-8065-11eb-9b95-a1f4e99082e0.png)

Let me know if you need other informations. I can send you the miz files, tacview, etc.

Thank you and keep up the good work!

**Comment by akaAgar** [comment]
Thanks for the detailed bug report.

Just fixed it. It was because of a typo in the "Soldier M249" unit ID. Downed pilots use a random infantry unit, so when "Soldier M249" was picked, it didn't spawn because of the error in the unit ID.

**Comment by cirmi00** [comment]
Wow, that was quick, thanks man. Modders and devs like yourself are the main reason why DCS is still a thing. We all thank you!
