### ISSUE TITLE
Can not save any edits with the briefing 

### ISSUE THREAD

**Issue by VCW3-admin** [akaAgar/briefing-room-for-dcs#131]
I've notice since the update that any edits in the mission editor done to the brief does not save. It will always revert to the original briefing generated by BriefingRoom. Any suggestions on this.

**Comment by john681611** [comment]
This seems to be an ED issue as we tested it and it happens with the DCS ME anyway. You can just use 7z and get to the mission file and update it there if you really need

**Comment by john681611** [comment]
Closing as we know its a base game issue
