### ISSUE TITLE
Aircraft spawning on airbases with too short runways for them

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#133]
Data needed: 
* Runway lengths for all maps
* Estimated minimum runway lengths for each aircraft (Community may be able to help, prioritize large aircraft, assume standard BR loadouts)

Solution:
* Add filter into airbase selection for minimum runway length.

Accepted limitations:
* Extra heavy payloads or high altitude runways may still be too short.

**Comment by jkaryan** [comment]
Can confirm, we've had our Su-25Ts and even A-10C IIs spawning on super short runways, with no chance of ever taking off, multiple times.

**Comment by john681611** [comment]
Apart from checking if runway spawns are generally set at either end and therefore calculating an approximate runway distance. We will also need to know the minimum runway for at least each playable aircraft (weather dependent IRL) or some level of aproximation.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.

**Comment by john681611** [comment]
Re-opening due to a report on it.

**Comment by john681611** [comment]
While we are currently short of data on specific aircraft data. Large aircraft have a default limit of >7000ft runway to spawn. Code has been written to support airbase selection logic for players. This will avoid airbases that aren't suitable (assuming aircraft has min runway lengths configured) or warn if you have specifically chosen an airbase and we think it will be an issue.

TODO: Implement for AI aircraft

**Comment by Wood-VCW3** [comment]
Still working on the runway lengths. Just been busy the last few days.
