### ISSUE TITLE
IA CAP Escorts Loadout problem

### ISSUE THREAD

**Issue by SpartanEsp** [akaAgar/briefing-room-for-dcs#137]
Hey !i have added some IA CAP Escorts to my missions and F16s are spawning to protect me but, they got just 2 AIM-120C and the rest are A/G weapons.

CAP Escorts should have full A/A Loadout

**Comment by john681611** [comment]
Added through BR or added through ME?

**Comment by SpartanEsp** [comment]
Added through BR on IA CAP Escort Parameter, 2 F-16Lot50 was spawned but with exactly 4 GBU and only 2 AIM-120C

After that, i have re-created the same mission with the same parameters on all settings, and then 2 F-15C was spawned with full A/A loadout.

Maybe the problem is the loadout on the F-16

**Comment by john681611** [comment]
Maybe checked the F-16 loadout in current code and it seemed fine mind making a mission that is a AA style mission with a F-16 and seeing if it still happens.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
