### ISSUE TITLE
Targeting Pod is missing on the default Loadout on the F-18 A/G Missions

### ISSUE THREAD

**Issue by SpartanEsp** [akaAgar/briefing-room-for-dcs#138]
The TGP should be equiped by default on A/G missions or Mixed Missions with the F-18 like Convoy Interception, Deep Strikes.... etc.

**Comment by john681611** [comment]
Maybe lets wait for 2.7 on this one then use the ATFLIR

**Comment by john681611** [comment]
Fix has been put in place if you want to make the change to your version just change the line highlited
https://github.com/akaAgar/briefing-room-for-dcs/pull/141/files#diff-8b1e9934e1cb80e573eaa6adfe65e6e17105fb2a2a813e049298cfe15f1188b1R37

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
