### ISSUE TITLE
Tomcat still not Loading in with chaff

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#142]
We finally got round to having a go at testing the latest version last night

f14 is still not spawning with the chaff launching rails, tested over 2 missions with no luck

**Comment by john681611** [comment]
Have you tried with a clean install or a test build?

**Comment by PSYKO-nz** [comment]
Haven’t tried the test build yet. This was posted before the test build came out, I have tried it with a clean install of the March 5 update. I allways make sure to do a clean install, just incase :)

both tomcats on the mission did not have chaff loaded

**Comment by john681611** [comment]
@PSYKO-nz  you seem to post lots of issues and ideas on here, It's much appreciated that you help us improve the game. Unfortunately, neither of us devs have the F-14. So if you could make yourself known on discord testing chat it would be helpful to have someone quickly test while we try and fix this.

**Comment by PSYKO-nz** [comment]
I’m not on discord, but I’ll take a look tomorrow and get setup and try make contact,

the big issue is I’m in New Zealand so my time zones are way out of whack from the rest of the planet lol

**Comment by john681611** [comment]
Please try this version:
https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/test-net5-210503-2105

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
