### ISSUE TITLE
Bomber escort late spawn crashed server then started with no f10 menu

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#144]
We started a bomber escort mission late spawn which crashed the server, after we finally got it to work we had no f10 menu to activate the bombers from

**Comment by john681611** [comment]
This has been fixed in terms of no F10 menu item. No idea about the crash

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
