### ISSUE TITLE
Bomber escort, bombers start way to far ahead

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#145]
After the late spawn issues we switched to the normal escort mission,

it ran great however the bomber spawned miles ahead of us, by the time we got airborne it was third of the way to the target, he was also a b1 doing it’s max speed. There was no way at all to catch him let alone protect him. Naturally he was killed by ai before we could do anything 

maybe make them take off at player airfield and even do a cold start?  

Or spawn them some distance behind the player airfield?

**Comment by john681611** [comment]
A partial fix for this is there is now a command spawned bomber objective.

Bombers should spawn around the home airfield (not the carrier if you decide to use one of them) This is the same logic for SEAD and CAP support.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
