### ISSUE TITLE
Spinning Carriers - Breaking Re-arm.

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#161]
Carrier groups want to spin around again trying to get to waypoint 0.
Think this also causes issues with re-arm not working

**Comment by avanrider** [comment]
I'm experienced the "Carriers Doing Doughnuts" as well. Makes landing a bit of a pain.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
