### ISSUE TITLE
Campaign Creation Bugs

### ISSUE THREAD

**Issue by sncollie** [akaAgar/briefing-room-for-dcs#163]
Just a couple of things with the campaign creation tool.  I created a Campaign flying the Mirage 2000 in The Caucasus.  I selected options for "Cold Start" and "No night missions".  The first mission started with me on the runway at night.   The briefing also said my side was "Russia" when I was flying for Blue (France in this case).  

The single mission creation works great, though!

Thanks again for this great tool.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template. New Campaign generator will come soon.
