### ISSUE TITLE
WWII missions generate modern ground units

### ISSUE THREAD

**Issue by 55Claw** [akaAgar/briefing-room-for-dcs#165]
[P-51.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6377361/P-51.zip)
When I create a WWII mission I get a mixed bunch of ground units. In the enclosed mission you'll find modern artillery, WWII units and British AAA units that defected to the Axis. Worse is when you have to go up agains modern SAMs :)

**Comment by john681611** [comment]
Got a template you can upload so we can replicate the error

**Comment by 55Claw** [comment]
The zip-file contains "test.brt". That is the template, correct?

**Comment by john681611** [comment]
yup thanks

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
