### ISSUE TITLE
MIG 19 missions bug

### ISSUE THREAD

**Issue by Gudari11** [akaAgar/briefing-room-for-dcs#166]
All the MIG19 missions don´t load (all the scenarios). The error  code is :error loading mission "/Saved Games/DCS/Missions/PARTIDAS RAPIDAS/MIG19//Operation Enduring Vanguard.miz": [string "mission = ..."]:1462: '}' expected (to close '{' at line 1461) near 'ADF_Selected_Frequency'. 

And the radio frequencies don't work, the 124 channel in the mig 21 and the mig 19

On the other hand, I want to congratulate you on your work, it´s a fantastic
 edito, for me the best!

**Comment by john681611** [comment]
Make the change in this PR and the Mig-19 should stop breaking the mission
https://github.com/akaAgar/briefing-room-for-dcs/pull/167

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
