### ISSUE TITLE
Viggen hot start crash

### ISSUE THREAD

**Issue by Gudari11** [akaAgar/briefing-room-for-dcs#169]
When  start a new "hot" mission, or when starting"cold" and inpout LOLA 9099, the mission crashed. The message is  in the picture
![crash](https://user-images.githubusercontent.com/83237805/116593334-41ed0780-a921-11eb-9ed7-87c5d120d23a.jpg)

**Comment by john681611** [comment]
Can't say much but it looks like the error occured within the Viggen its self. it could be a config bug on our side.

**Comment by flappiefh** [comment]
Bug reproduced. I believe this bug is the one that had been fixed not so long ago. Agar once told me the error was the AJS37 was considered an helicopter, not a fighter.

**Comment by john681611** [comment]
huh @akaAgar?

**Comment by Gudari11** [comment]
Now, with the last DCS update, it works again!

**Comment by john681611** [comment]
So its working now can we close this issue?

**Comment by flappiefh** [comment]
Confirmed. I generated a new MP mission with Viggen slots and DCS didn't crash when I entered a Viggen.
