### ISSUE TITLE
Language option

### ISSUE THREAD

**Issue by ghost** [akaAgar/briefing-room-for-dcs#17]
Hello, is it possible to choose the language? For Spanish I volunteer, after seeing how the archives are I don't see any difficulty in translating it (in Headquarters for DCS we were already in contact)

**Comment by john681611** [comment]
Not sure how much English is hardcoded in the code but. I expect for this we would have to do the UI too which means we would need to implement a strings system. pretty sure it's not hard just may take some time to implement.

**Comment by AzzameenF18** [comment]
From what I have seen, it is almost everything (at least the briefing) within the ini of the database folder. From the interface, I haven't found anything. Maybe doing a redirection to (for example, *_EN.ini for English *_ES.ini for Spanish) would be solved. It's just an idea
*** Translated with www.DeepL.com/Translator (free version) ***

**Comment by akaAgar** [comment]
Hi Azzameen. For the moment many strings (dates, ordinal adjectives, etc) are hardcoded, but my goal is to move all constants and strings to ini files so anything can be modded easily, so it will be possible to translate everything (including the interface).

Now regarding proper localization, which would involve having multiple strings in each file and not having to replace all files in the database directory each time an user wants to change the language, I may add it later on, but unlike in HQ4DCS, where it was one of my priorities, I kinda put it on the backburne. Making everything localizable, especially in a program which includes lots of randomly generated strings, slows down the work quite a bit, and my priority is on adding new mission features.

But that doesn't mean i'm not interested in localization. But as mission, briefing and coalitions structures may change quite a bit in the next versions (I'm working right now on a new coalition system which will allow BR4DCS to generate missions featuring all DCS World countries with the proper units for the period, but will change the way briefings are generated), I'd rather wait before implementing a proper localization system.

**Comment by john681611** [comment]
Long time coming but this is now being started

- [ ] Briefing
- [ ] UI
- [ ] ScriptedText
