### ISSUE TITLE
BriefingRoom for DCS Stable version support

### ISSUE THREAD

**Issue by jchcommun** [akaAgar/briefing-room-for-dcs#170]
Hi,

BriefingRoom seems to be a very helpful tool I'd like to use, but when I try to open a generated mission with DCS stable version's mission editor, I see some odd things, like plane units for which I can't access the properties. I guess it must be because the tool generates missions in DCS open beta format(?).

Anyway, I wondered if it would be possible to enhance BriefingRoom so the target DCS version (open beta or stable) could be chosen as a parameter?

I guess it could be interesting for other virtual pilots flying exclusively the stable version, too.
Thanks.

**Comment by john681611** [comment]
Future versions will only support 2.7 or greater. Unfortunately, this is down to the mission layout that DCS generates breaking in 2.7 and the majority of our userbase seems to use beta. Hopefully once stable gets to 2.7 then it should be generally compatible again.

Currently, we break the ME in a few ways in 2.7  and we are undergoing a bit of a re-write to untangle some of the mess,

**Comment by jchcommun** [comment]
Hi,

Thanks for your answer. Too bad then, but your tool, your decision, I understand, no problem.

**Comment by john681611** [comment]
Older versions should still be compatible but issues like properties failing to show in ME were issues we faced and continue to face in Beta basically its bad configs on our end if you look back through the closed PRs you should be able to find fixes for many bugged aircraft in the older downloads.

**Comment by jchcommun** [comment]
OK, thanks.
