### ISSUE TITLE
Flight frequencies

### ISSUE THREAD

**Issue by Valk77** [akaAgar/briefing-room-for-dcs#18]
The AI flight members are using an UHF frequency. For the F-16 this is problematic because AWACS and tankers also use UHF frequencies and the Viper only has one UHF radio. The AI flight should be on a VHF frequency.

**Comment by john681611** [comment]
We generally run on the default frequencies that DCS gives in the editor (adjusting a little for multiple aircraft). You are always welcome to go into the editor and make these changes yourself if you do find it a major pain. 

In future, we will be trying to move radio values into the database so you can modify them easily.

**Comment by john681611** [comment]
Closing due to age.
