### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#180]
I figured that with the beta test builds that it would be a good thing to have a location to post messages about the tests/versions.

just to make general communication about these builds easier.

so we can use this thread for it.

**Comment by PSYKO-nz** [comment]
Me and my test crew will test the latest build tomorrow night, I’ll post results here

**Comment by john681611** [comment]
Honestly guys this fits discord rather than issue tracking

**Comment by PSYKO-nz** [comment]
I’ll get discord installed this week :)

**Comment by john681611** [comment]
We have a testing channel these kinda reports do seem to fit.
