### ISSUE TITLE
first test of NET5 210504-1705

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#181]
we had a very successful test of the latest test build tonight. (on Syria map)

tomcat was able to deploy chaff in the normal way, well-done guys! this saved my ass 4 times tonight

f18 and a10c2 were able to choose skins when set to USA, still can't choose skins when set to CJTFBlue, no big deal just set them as usa
     - is it possible to set all units by default top whatever the coalition/blue setting is to save manually adjusting all the aircraft?

2 issues we discovered.

1, we did a 3 target deep strike, the first target functioned as normal, we had a little trouble spotting it but a smoke round solved that problem, and we destroyed the target fine, however, the remaining 2 targets did not seem to spawn, we asked for smoke and coordinates but got back a no joy. the vehicles protecting the area spawned fine, just the targets themselves did not show up, we searched and searched but couldn't see anything

2, on Syria there are some hangars, there beige, I imagine their sand or clay covered, they are not big enough for the tomcat or a10 to fit in, there are most likely more aircraft that cant fit in as well, can I suggest ruling out those spawn points? it ruins the mission if you have to remake the mission because some of the planes spawn in and break

some more good info, 
the markers over the targets worked fine. 
we used fog of war mode on the map markers and that was sweet, worked as expected
the labels seemed to be set to dot only which was awesome.
all other special settings appeared to work too, we even had an engine failure in an a10 on the way to the target!
in general, everything worked fine, with the exception of the 2 issues above!

the mission is attached below if you need it for tests

well done guys, heaps of progress!!!

[mission.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6426328/mission.zip)

**Comment by john681611** [comment]
Closing this ticket as its not really a single issue.
1. is logged as #184
2. is logged as #133

 Skins are limited by country unless its not configured so nothing we can do about lack of skins under CJTFBlue
