### ISSUE TITLE
Laser Spot Search function not working in some Deep Strike missions

### ISSUE THREAD

**Issue by fede-vaccaro** [akaAgar/briefing-room-for-dcs#182]
I generated a Deep Strike mission and set an Hornet with its TGP. After requesting to the JTAC to lase the target, I was unable to find the target with the Laser Search function of the Hornet's Litening TGP. The objective was a (big) Silo.

I was definitely looking towards the correct area,  I also requested the smoke signal and obtained it correctly. At first I was afraid it was an issue related to the Hornet or the Lasing script, but I tried a simpler mission where the targets were some BMPs/BTRs and it worked correctly, so I believe it was mainly related to the building itself.

**Comment by 55Claw** [comment]
I tried this in an interdiction mission and concur. I first used the Litening pod but got no LSS lock. Than I tried the Atflir also with no lock. A laser guided Maverick locked to target succefully so the JTAC is actually lasing the target. I included the mission and the template (perhaps better to delete the enemy CAP and that nasty SAM near the target for an uninterrupted test)
[FA-18C.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6429200/FA-18C.zip)

**Comment by john681611** [comment]
Interesting I've just run a Deep Strike Mission and While LSS didn't work the Laser guided bombs did guide properly and hit the target.

**Comment by john681611** [comment]
Looking at the code and the fact that every LGB worked fine in my mission I'm inclined to say this is laser obscuring somehow or a DCS issue

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
