### ISSUE TITLE
Singleplayer CAP escorts sometimes turn back and RTB when there's no target to engage during the first minutes of the mission

### ISSUE THREAD

**Issue by akaAgar** [akaAgar/briefing-room-for-dcs#19]

**Comment by john681611** [comment]
This may be a bug with DCS its self as it was mentioned here https://forums.eagle.ru/topic/254461-official-news-2021/?tab=comments#comment-4546645

**Comment by akaAgar** [comment]
Sorta fixed. The single-player escorts now use the MP behavior (escorts go straight to the target zone once players have taken off instead of escorting the player aircraft). I may switch back to the old SP escort behavior once ED has fixed their escort AI, but for the moment it works just as well without using the "escort" task.
