### ISSUE TITLE
Spawning enemy AI aircraft spawning near objectives, Way too close

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#194]
This is a big and annoying issue that had plagued us for our last few tests of the beta.

When an objective/mission is complete and the next lot of enemy aircraft spawns in they spawn right near the objective area, they just appear out of nowhere 10-20nm (at a guess) from the target area. Leaving no time for the CAP flight to do anything about it.

Last time out I was flying cap over 2 a10s working on a moving vehicle interdiction, some mig 29s spawned about 20nm away from the target, 50nm away from me,  I started to work the intercept on them, short notice but I was managing it, then as I drew up to an engagement range out of some externally powerful stealth cloaking device co alt with me at 30,000ft 2 mig23s appeared about 15nm on my 3, I had to drop the intercept to kill the mig 23s by the time I had done that the mig 29s had killed the a10s to death.

Are you able to make it so spawning aircraft either spawn at a nearby airfield and scramble to attack you or that they come from far enough away that it feels realistic for them coming from a base nearby, or an on station area nearb, it really sucks when the mission ends because a fox spawned in the hen house. No chance to save them, no point doing a barcap to protect the airspace when there spawning that close. This issue has been a big buzz kill in some otherwise epic missions. Other than this at this stage we haven’t found anything really wrong! We’re loving it

**Comment by taerdryn** [comment]
I just experienced this on an Interdiction (Idle Targets) mission and I have to agree that this is quite a major issue - aircraft spawning in after an objective has been completed is fine, but they should definitely not be spawning right beside it. They need to be at least 60-100nm away from the objective/flights.

It feels very cheap to have a MiG-29 spawn in already spiking, and then launching on friendly aircraft in under 60 seconds.

**Comment by PSYKO-nz** [comment]
Happened again last night, this time 2 migs spawned in between the 3 objectives, 3 frigates, I was circling around the ships knowing that doing a bar cap doesn’t work but I was still too far away to protect the strike package, luckily one of the strikers was able to get a couple aim 9s off and save the day but still it’s frustrating 

can I also suggest along with spawning them further away that a random spawn might be a cool feature. At the moment they spawn at the start, when an objective is complete or when the mission is complete, a way for a flight to randomly spawn maybe 45 mins in or 90 mins in or what ever would add some complexity to the job of the escorts meaning that the strike package could be attacked during an attack, just a thought, maybe something for the future tho, spawning the enemy aircraft further away needs to be sorted first I think, just a thought

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
