### ISSUE TITLE
Add L-61 JCI 

### ISSUE THREAD

**Issue by Ala46vWidowmaker** [akaAgar/briefing-room-for-dcs#195]
Hi! Can you Add the L-61 JCI like a carrier? (Spanish navy)
https://www.desdemicabina.com/Descarga/Download/
And can you add the selection of new air tankers? Thanks!

**Comment by CJBeltza** [comment]
Yes, please. The L61 carrier forming a task force with the frigates included in the mod desdemicabina . And the possibility to select the air tanker KC-130. Good request, Widowmaker.

**Comment by desdemicabina-simulation** [comment]
Good afternoon! First of all, thank you for this fantastic job. I´m the creator of the  L61 Juan Carlos I, the F100 frigates, the L52 Castilla and the future Hobart and Canberra . If you need any documentation to be able to add our units to your program I´m happy to help. All the best.

desdemicabina-simulation

**Comment by john681611** [comment]
Edited name to be a single issue.

@desdemicabina-simulation vehicles are configured up in the Database folder which means you can mod your carrier into on your own version. Though if you want to make it into a release a PR is always welcome.

Here is some basic docs but tbh carriers are pretty simple.
https://github.com/akaAgar/briefing-room-for-dcs/blob/main/Modder's%20manual.md#databaseunits-directory

Two Items of Note:
* We make some assumptions about how carriers function based on the Vanilla carriers if your carrier is configured like them it should be pretty much plug and play.
* In recent beta builds we have moved to more of a carrier task force design (to avoid spinning carriers and more realistic fleets) these work more like SAM sites and its best if you use a suitable existing carrier as a template and replace IDs

**Comment by desdemicabina-simulation** [comment]
Thanks a lot!


Best regards,

Jose Arocha

desdemicabina-simulation
________________________________
De: John Harvey ***@***.***>
Enviado: miércoles, 2 de junio de 2021 14:29
Para: akaAgar/briefing-room-for-dcs ***@***.***>
Cc: desdemicabina-simulation ***@***.***>; Mention ***@***.***>
Asunto: Re: [akaAgar/briefing-room-for-dcs] Add L-61 JCI (#195)


Edited name to be a single issue.

@desdemicabina-simulation<https://github.com/desdemicabina-simulation> vehicles are configured up in the Database folder which means you can mod your carrier into on your own version. Though if you want to make it into a release a PR is always welcome.

Here is some basic docs but tbh carriers are pretty simple.
https://github.com/akaAgar/briefing-room-for-dcs/blob/main/Modder's%20manual.md#databaseunits-directory

Two Items of Note:

  *   We make some assumptions about how carriers function based on the Vanilla carriers if your carrier is configured like them it should be pretty much plug and play.
  *   In recent beta builds we have moved to more of a carrier task force design (to avoid spinning carriers and more realistic fleets) these work more like SAM sites and its best if you use a suitable existing carrier as a template and replace IDs

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
