### ISSUE TITLE
Choose the type of tanker in the drop-down menu

### ISSUE THREAD

**Issue by Ala46vWidowmaker** [akaAgar/briefing-room-for-dcs#196]
be able to choose the type of tanker in the drop-down menu.
The tanker does not appear the tacan if you change the model, for example from KC-135 to MPRS, the tacan disappears.
Another problem is the liveries since even if you select a country, it does not let you choose since it creates two coalitions

**Comment by john681611** [comment]
edited title for clarity

**Comment by Ala46vWidowmaker** [comment]
Hi! What I want to say is that by default the kc-135 appears on the blue side and the A-50 on the red side. How can you choose another tanker? Can it be added as an option on the menu and its tacan as well? Thank you!
________________________________
De: John Harvey ***@***.***>
Enviado: miércoles, 2 de junio de 2021 15:29
Para: akaAgar/briefing-room-for-dcs ***@***.***>
Cc: Ala46vWidowmaker ***@***.***>; Author ***@***.***>
Asunto: Re: [akaAgar/briefing-room-for-dcs] Choose the type of tanker in the drop-down menu (#196)


edited title for clarity

**Comment by Ala46vWidowmaker** [comment]
Ok OK Thanks!

**Comment by john681611** [comment]
Feature added in 0.5
