### ISSUE TITLE
Feature: Mission End

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#20]
It would be nice for missions to end when objectives complete and no players are flying. Should be an option though

**Comment by akaAgar** [comment]
Oh yeah, that's a good idea. Pretty easy to implement too.

**Comment by john681611** [comment]
I'll see If I can implement it as an optional feature

**Comment by akaAgar** [comment]
There's no "end mission" command in the Lua script (as far as I know), so you'll have to create a "end mission when flag X is true" trigger in the mission editor (which will be stored in the "mission" file), then set this flag to true when the mission is complete and all players have landed (maybe check if there's still a player in the air each time a player landing event happens) using trigger.action.setUserFlag().
