### ISSUE TITLE
Redfor aircraft low to the ground

### ISSUE THREAD

**Issue by ocgadmin** [akaAgar/briefing-room-for-dcs#203]
Situation, enemies
Air defense: High
Air Force High 
etc
Enemy aircraft fly extremely low and slow, Nose up. and crash into mountain
[Operation Allied Dragon.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6651929/Operation.Allied.Dragon.zip)

**Comment by john681611** [comment]
We last saw this bug a long time ago, can you make sure you're running the latest release.

The only other situation we see this is in is if the aircraft has been left for a long time and they run out of fuel and the AI limp home though I've yet to see them crash into mountains on low fuel.

**Comment by ocgadmin** [comment]
Running latest version.
Will do a reinstall in case something was left over from previous version
Current version: 0.4.104.21
Targeted DCS World version: 2.7.0.4625

**Comment by john681611** [comment]
re-do your database that is likely the source

**Comment by ocgadmin** [comment]
Will do Thanks for the quick response

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
