### ISSUE TITLE
Easy comms not working 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#204]
Played a few missions without the “no easy comms” option selected and we still had to manually do the radios, ie, easy comms we’re not working

**Comment by john681611** [comment]
I think this option just forces it off it doesn't turn it on unless you have it on in your options.

**Comment by PSYKO-nz** [comment]
I’ll take a look but I’m pretty sure our options are set to easy comms, I’ll check and get back to you

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
