### ISSUE TITLE
Add the MI-24 hind to the helis

### ISSUE THREAD

**Issue by Gudari11** [akaAgar/briefing-room-for-dcs#208]
There are few missions for the new module. It would be great to add the hind to flying helicopters. Thanks again!!

**Comment by john681611** [comment]
It's been done but only in the new re-write unfortunately. No ETA on when it will release but you may be able to back port the unit config in the Database to get it to work.

**Comment by john681611** [comment]
[Mi-24P.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6742652/Mi-24P.zip)
This was submitted by one of our discord testers for you to use. I'm closing this off as it is fixed in the code.
