### ISSUE TITLE
Weapons going through target?

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#211]
We flew a deep strike the other day, target 1 was a oil tank, we shot gau8, rockets and 2 jdam at it, all of them went through it, as in, in one side and out the other.

the other 2 targets didn’t have the problem just objective 1. We finally blew it up after dropping another 2x 2000 bombs on it from directly above it, seems that attacks from the side did nothing but vertical ones worked

Not sure that caused the issue it may be a dcs thing not a briefing room thing but it was some what annoying

**Comment by john681611** [comment]
Sounds like a DCS bug to me but thanks for the info if you can get us the exact unit we can take it out of the pool to avoid the issue re-occuring.

I do also recommend reporting to ED to get it fixed.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
