### ISSUE TITLE
MiG-19P error

### ISSUE THREAD

**Issue by apollon01** [akaAgar/briefing-room-for-dcs#213]
Hello,

just a shout to you that the missions generated for MiG-19P return error when trying to load them up.

The error message is:

Error loading mission "XXXYYYZZZ.miz": [string "mission = ..."]:2954:'}'expected (to close '{at line 2953) near 'ADF_Selected_Frequency'

Please have a look at it if you have some time.

Thanks!
Milan

**Comment by john681611** [comment]
We fixed this please make sure your version is the latest and you have completely deleted the original database. If its not been fixed in the last release then it will come out fixed in the next one.

**Comment by apollon01** [comment]
Thanks for your reply.

The error comes from the latest v04.104.21.

I will wait for the next version then. No problem. Thanks.

**Comment by john681611** [comment]
#167 if you wanna fix it yourself I just found the PR
