### ISSUE TITLE
release-210703-1807 - gui link just opens chrome, but it is possible to get working - how to in description

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#221]
so in this version, it is possible to get working, first, open the folder, then click briefing room gui exe, once it loads click the briefing room web gui shortcut, this just opens up chrome at the moment, so go back to the cmd and copy http://localhost:5000 paste that into the browsers address bar and it opens

once you get in  it is awesome, you have outdone yourselves

**Comment by john681611** [comment]
yup we found this issue right away we are working on a desktop app to make this a ton simpler.
