### ISSUE TITLE
JTAC no visual on target

### ISSUE THREAD

**Issue by Cathnan** [akaAgar/briefing-room-for-dcs#225]
JTAC has no visual on target even in perfect conditions. Requesting Laser designation triggers an appropriate response. LST with tgp doesn't find a laser designation in the assumed target area. Requesting designation gives the same result regardless of wether still parked on the carrier or circiling the target area.

The mission was created as follows:
Theater: Marianas Island

Environment:
- Season: Winter
- Time of day: Random
- WeatherPreset: Light scattered clouds
- Wind: Random

Objective:
- Destroy all Idle any vehicles
- Target count: Low
- Features: Laser designation

Flight Groups:
- Aircraft: F/A-18C Hornet
- Payload: Air to ground
- Start location: parking cold
- Carrier: USS George Washington
- AI Wingmen

Situation:
Enemies
- Air Defense: Low
- Air Force: None

Options:
Mission Features: Enemy AWACS; Friendly AWACS
Unit mods: DCS: WWII Assets Pack
Mission Options: Enable civillian traffic

**Comment by john681611** [comment]
Should be fixed now try the latest release

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
