### ISSUE TITLE
1907 - server crashing on Marianas map? make sure m map is installed on server - how-to in dsc

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#231]
originally I thought this was a bug however I tried other maps successfully. turns out when the update happened that added Marianas the map wasn't auto-installed, YOU HAVE TO INSTALL IT MANUALLY ON THE SERVERS. 

here's how...

https://forums.eagle.ru/topic/275996-how-do-i-install-the-mariana-map-on-the-dedicated-server/

after that's done works fine

**Comment by john681611** [comment]
This kinda stuff needs to be shared on our discord as its not an issue or feature request. Side note what is 1907?

**Comment by PSYKO-nz** [comment]
1907 is the last 4 numbers for the latest release 

I keep meaning to sort out discord out but allways seem to get distracted by other things. To be fair this post actually started as an issue but after I figured the problem out I changed it to what it is now
