### ISSUE TITLE
beta-release-210709-1807  -Weapon loadout not working

### ISSUE THREAD

**Issue by JoseCvelez** [akaAgar/briefing-room-for-dcs#232]
I noticed UH-1H loadout is not showing up during the missions. I selected Decade2000, and tried several options, but none worked. It is also not possible to select the weapons loadout at the Mission Planner or the Mission Editor. The weapon loadout screen does not show up. 

p.s. the additional options for targets is awesome!

**Comment by john681611** [comment]
This is likely caused by a Known issue where the aircraft doesn't have a suitable role assigned (currently we don't have this info extracted from DCS) This causes issues with the planner and ME. You should be able to re-arm

**Comment by john681611** [comment]
ref #168
