### ISSUE TITLE
beta-release-210709-1807 - no AWACS or tankers

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#233]
Did 2 tests with awacs and tankers for friendly selected none showed up in
Either mission

**Comment by john681611** [comment]
AWACS and tankers are now optional and default off. Turn them on in mission features and see if the issue still occures.

**Comment by PSYKO-nz** [comment]
Awacs and tankers were turned on in both missions.

new interface is great by the way, easy to understand!

**Comment by john681611** [comment]
Huh have you tried with latest version?

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
