### ISSUE TITLE
beta-release-210709-1807 - no radio alerts to destroyed targets/objectives 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#234]
In out 2 tests we had no reports of effective weapons or mission/objectives complete

**Comment by john681611** [comment]
We fixed this please try in latest release

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
