### ISSUE TITLE
beta-release-210709-1807 - exe crash.

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#235]
When I tried to export a mission there was a crash of the program but I was unable to find the log for it.

I will try recreate it and post more info here

**Comment by PSYKO-nz** [comment]
I’ve been unable to replicate the bug as yet, will keep testing 


Also. The new interface is amazing!

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
