### ISSUE TITLE
beta-release-210709-1807 - no enemy ai aircraft 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#236]
We did 2 missions both with the enemy airforce set to average and in both missions we saw none

**Comment by john681611** [comment]
Even after objective completion. Note please re-try this on the latest release.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
