### ISSUE TITLE
beta-release-210709-1807 - a10c2 change skin not working 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#237]
Did a test with the a10c set to USA and CJTFBlue and could not change skins on either setting

**Comment by john681611** [comment]
Hmm confirmed it myself. Odd this one.

**Comment by john681611** [comment]
OK this is fixed in code, just waiting to see if anything else pops up before I kick off a beta build.

**Comment by PSYKO-nz** [comment]
Seems to be fixed in most recent version
