### ISSUE TITLE
Unhandled exception - C:\Users\ambro\.nuget\packages\blazored.typehead\4.6.0\staticwebassets\.

### ISSUE THREAD

**Issue by Aarnoman** [akaAgar/briefing-room-for-dcs#238]
On current release version of briefing room (0.5.107.18)
To reproduce: 
1) MicrosoftEdgeWebview2Setup installed.
2) Run BriefingRoomGUI.exe
3) Unhandled exception occurs.

Win 10, x64.
Full error output: https://pastebin.com/GTNdjFJV

**Comment by Aarnoman** [comment]
Looks to me like the program currently references one of the programmers directories, as ambro is not my username.

**Comment by Aarnoman** [comment]
Further information: I have just built a release based on a pull from main branch, with it performing as intended and no exception thrown. Is someone able to test this build version to see if they encounter the exception when used on a different user?

**Comment by john681611** [comment]
Yeah looks like the release @akaAgar did miss something please use the alternate build here:
https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/beta-release-210718-0507
Note the GUI.exe won't work but you can use the Desktop.exe

**Comment by Aarnoman** [comment]
Can confirm alternate build provided by @john681611 works as intended.
