### ISSUE TITLE
Possible missing scrollbar?

### ISSUE THREAD

**Issue by Viking355** [akaAgar/briefing-room-for-dcs#240]
### Brief Description: 

Full Mission generator -> Context tab -> Red & Blue coalition selection

The options stop at Germany, and appear to be alphabetical.  It seems a bit odd that Argentina and Belgium made the cut, but Russia, Iran and USAF Aggressors didn't, so I suspect there's supposed to be a scroll bar on that drop-down that isn't showing up.

**Comment by john681611** [comment]
It's a Typeahead box if you click on it you  should be able to search for your coalition
