### ISSUE TITLE
Error when loading anti-ship mission

### ISSUE THREAD

**Issue by Tabmo1** [akaAgar/briefing-room-for-dcs#241]
### Brief Description: 
Anti-ship missions generated with BR result in a following error in DCS on load.
![Error ASM](https://user-images.githubusercontent.com/87617715/126079452-b3616587-054c-45cc-90cb-281fe8391ea8.png)

Changed file extensions to txt to upload to GitHub.

### Expected: 
Loaded mission

#### Template File: 
[Default - Copy.txt](https://github.com/akaAgar/briefing-room-for-dcs/files/6836814/Default.-.Copy.txt)

####  Example Mission File: [PersianGulf - Operation Secure Quest.txt](https://github.com/akaAgar/briefing-room-for-dcs/files/6836815/PersianGulf.-.Operation.Secure.Quest.txt)

Mission modified: N

**Comment by john681611** [comment]
Can you please upload the original files not text files please and we can get working on this.

**Comment by akaAgar** [comment]
Looks like values $RADIOBAND$ and $RADIOFREQUENCY$ (found in UnitShip.lua) were not replaced for ship targets. I added a check for non-replaced values in the Miz generator. It works now.
