### ISSUE TITLE
DSMC Compatability

### ISSUE THREAD

**Issue by JCae2798** [akaAgar/briefing-room-for-dcs#243]
Not sure if this is was suppose to work by design but I'm using this in conjunction with DSMC to allow continuation of missions in single play.  When i complete a mission and restart the mission with units deleted, the mission status does not show the objective as complete.  I have some basic knowledge of scripting so when i looked at the script.lua it seems it checks for completed missions but it's not updating objectives.

### How does it work: 
DSMC is a mod that takes a snapshot of dead units and carries over mission details into the next session.  When i look at the next mission i can confirm the unit IDs are deleted.  So looking at the script.lua when objective is looking for these unit IDs and they dont exist it should complete the objective

### Why can't it be done in the ME quickly: 
Since objectives are controlled via LUA, there is no control in ME.  My ask is that when script.lua is checking objective status if Unit IDs no longer exist that it marks the objectives complete.  As a test when i ask AI JTAC to pop smoke on target i do get conformation that the target does not exist.  So the objectives are not completing when mission starts but does work fine during mission itself when units are killed.  Again this only happens on mission start when units have been deleted.

EXTRA;
As i mentioned i have some scripting knowledge.  If there is some testing or somehow to modify the script.lua to test this further i'd be happy to do so.  Looking at the existing code i cannot determine why the existing objectives are not completing when unit IDs are missing at mission start.

**Comment by JCae2798** [comment]
Quick test; 
1. Create mission with objective and ground units.  
2. Edit mission and delete units
3. Start mission and ask for mission status.

Quick workaround
Edit script.lua and change objective status from false to true for complete (complete = false);
briefingRoom.mission.objectives[6] = { complete = false, groupID = 7, hideTargetCount = false, name = "HOWL", targetCategory = Unit.Category.GROUND_UNIT, task = "Destroy all artillery designated objective HOWL.", unitsCount = 2, unitsID = { 27, 28 } }
briefingRoom.f10Menu.objectives[6] = missionCommands.addSubMenuForCoalition(coalition.side.BLUE, "Objective HOWL", nil)

**Comment by john681611** [comment]
@JCae2798 Can you join our discord and discuss this.

**Comment by JCae2798** [comment]
Hey there John.  Haven't been able to play much lately due to a recent birth of a child, but happy to share my thoughts and can hopefully test in the future.  Thanks

**Comment by john681611** [comment]
Congratulations!

**Comment by john681611** [comment]
I wonder would it be suitable if we just silently completed any objectives at the start maybe just with a message

**Comment by john681611** [comment]
Code added to auto-complete an objective if no target units are left on start. Also we correct the number of units needing to be killed if that has changed.

**Comment by john681611** [comment]
Closing as Released
