### ISSUE TITLE
No map markers (orange circles) after first waypoint (MP)

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#247]
### Brief Description: 
 No map markers on the map (orange circles)

### Expected: 
 When this feature was enabled in previous versions it placed dcs markers on the waypoints in the mission, would be cool to have them back

[files.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6891975/files.zip)

**Comment by john681611** [comment]
I believe this has been removed due to ED adding in the waypoints back on the map.

**Comment by PSYKO-nz** [comment]
So we can manually place them in game but the mission builder can’t just place them for us automatically? That’s a bit silly, is there any chance to get them back?

also while I’m on the subject, I think the new IP waypoints should be removed if you don’t have “extra map markers” selected, if you have the extra markers it should be there but if you only want the mission objectives waypoints and nothin else the IP waypoint shouldn’t be there, also there’s the be, so if your doing multiple objectives you only have then IP for one objectives. Just a thought while on the waypoints subject :)

**Comment by john681611** [comment]
Ok to be more accurate our map markers probably haven't been re-implemented due to ED adding in the waypoints

**Comment by PSYKO-nz** [comment]
Update:

The first objective had a orange marker on it however the remaining waypoints did not

**Comment by john681611** [comment]
Fixed and moved under Mission Option:
![image](https://user-images.githubusercontent.com/10814889/132099703-d61261a5-1d00-4218-bee9-3aa3d7c5474c.png)
This is default on

**Comment by john681611** [comment]
Released Closing
