### ISSUE TITLE
No structures spawned, no JTAC available in the radio menu

### ISSUE THREAD

**Issue by jubuttib** [akaAgar/briefing-room-for-dcs#249]
### Brief Description: 
Generated a mission with two objectives, one was for destroying structures, yet no structures were generated. Or at the very least we couldn't find them, even looking at the file in mission editor. 

Additionally JTAC was supposed to be available, but didn't show up in the radio menu.

### Expected: 
Structures should be generated, JTAC should be available.

#### Template File: I saved the template over Default.brt
[Default.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6892242/Default.zip)

####  Example Mission File: 
[MarianaIslands - Operation Urgent Fox.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/6892184/MarianaIslands.-.Operation.Urgent.Fox.zip)

Mission modified: N

**Comment by eranur-86** [comment]
Can confirm. Today generated a Mission for Interdiction, JTAC and 2nd Mission Deepstrike Structure.
The Structure was not generated.

**Comment by john681611** [comment]
Released Closing
