### ISSUE TITLE
S3 tanker near carrier for recovery tanking

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#250]
### Brief Description: 
have a KS3 available as a recovery tanker for the carrier

### How does it work: 
if you are low on gas or bolter too many times you may need to get a topping up of your fuel so you can make it aboard, this would be a very handy feature in carrier missions!

### Why can't it be done in the ME quickly: 
it needs to orbit the carrier or be flying near it, also there are normal tankers as options in the builder, there should be ones for the navy guys :)

**Comment by john681611** [comment]
Is this a thing IRL?

S3 should definitely be an available tanker if not then its a bug.

But if your running out of fuel then landing is surely better than trying to deal with a tanker.

Maybe just me because I suck at AA Fueling and have yet to spend the requisite time struggling to do it. 😄

**Comment by PSYKO-nz** [comment]
Haha fair enough, the s3 is the worst too,

Currently in the briefing room missions there is no s3 option.

irl the s3 is dispatched during operations so that any one who needs a bit of extra gas for landing can get some. It’s not there to fill the tanks completely of the aircraft in need but to get the aircraft’s fuel state to a position where they have enough gas to make a few attempts at landing.

so say I’m low on gas, I’ve made it to the ship but I’ve only got 2000ibs left of gas, that’s enough for one go at coming aboard, if I bolter I’m screwed, so I would hit the
Tanker and take on an extra 2000ibs (or what ever) so I have the fuel to make a few approaches, if I am having a bad night and still can’t trap I would again hit the tanker, this goes on Untill the tanker is out of gas, I trap or I get send to a divert, when I would take on more gas before I left

so it’s not like the big tankers where there job is to keep you topped off on transit flights or to fill you all the way up before your push to the target the s3s job in the recovery role is to give you fuel if you need it for landing so you have one less thing to stress about when landing on the cv :) hopefully that explanation makes sense haha

**Comment by PSYKO-nz** [comment]
I’m working on something that might work for this, I’ll keep you posted
