### ISSUE TITLE
Soldiers near objectives are immortal 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#253]
### Brief Description: 
2 a10s attacked with gun, rocket a bomb and then a maverick to the face and none of the soldiers that were spawned next to the objective died

### Expected: 
 There should be nothing left of them

**Comment by john681611** [comment]
Noticed this on a mission they should not be immortal but I think they may be setup to keep FPS up will check it out.

**Comment by john681611** [comment]
#265 has a fix for this hidden in it

**Comment by john681611** [comment]
Released Closing
