### ISSUE TITLE
Aircraft spawning in unsittable location  (post all instances here) 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#254]
### Brief Description: 
 Spawning in in a large jet like the tomcat some of the hangers are 2 small for it to spawn in and it damages the aircraft, also happens with tall
Aircraft 

### Expected: 
 Spawn in a safe place

**Comment by john681611** [comment]
Ok was waiting for this post to appear because it's a pain to figure this out and tbh it needs the community to locate these positions.  

I'm officially making this the Unsuitable starting position post.  I'll edit this post to fulfill this role
