### ISSUE TITLE
Add several objectives at one waypoint 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#255]
### Brief Description: 
 Have the ability for multiple objectives to be spawned at one location 

### How does it work: 
 Allow the mission builder to define what objectives spawn at what waypoint 

ie, there is a military structure near an airport there is also some trucks and a sam site, they are all located around the same airport and all need to be destroyed but are separate objectives

this way we could build a much bigger picture at the targets and it would also mean that you could do multiple objectives at multiple waypoints if wanted, means a more saturated target area instead of one building in the middle of a field with nothing around it!

Then a long flight to another target sitting in a field with nothing around it

**Comment by john681611** [comment]
Plan: Internally these are considered Sub Objectives Air can spawn at same spot else nearest valid spot (avoiding overlap issues)
TODO:
- [x] Create SubObjective props in template and record
- [x] UI add/remove/edit
- [] Add SubObjective validation A:ships & land don't mix B: Airbase spawn is not valid as subObj
- [] Spawn SubObjective Units
- [] Add Normal Objective tracking & waypoints

**Comment by john681611** [comment]
Closing as Released
