### ISSUE TITLE
Imbedded air defence worked at wp2 but not wp1

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#256]
### Brief Description: 
 Embedded air defence was set for both waypoints but only showed up at one of them, also it was only 1 gun too

### Expected: 
 Both targets should have had aaa, maybe more of the too?

**Comment by john681611** [comment]
Embedded air defense = "Chance (according to coalition air defense settings) to spawn short-range air-defense near the target" it linked to general AA rating. Closing as this isn't really a bug
