### ISSUE TITLE
More sides in coalition?

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#257]
### Brief Description: 
 Add more sides to coalition

### How does it work: 
 Currently there are 10 options
Algeria
Allies
Argentina
Axis
Belgium
Canada 
China
EU
France 
Germany

USA and Russia are not options so if you click off one you have to reset the builder to get it back 

I’m assuming that the reason for this is because it’s a beta build and it cuts down on work, but in the future more sides would be cool, just the main ones 

but USA and Russia need to be added in ASAP

**Comment by john681611** [comment]
It's a Typeahead. Like aircraft, you search in it. But I will log an issue that its not clear and the dropdown doesn't show everything.
