### ISSUE TITLE
No extra enemy aircraft coming after initial wave - half bug half enhancement 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#259]
### Brief Description: 
We had all settings set to average for airforce and air defences and everything else we could find, but after the initial wave of aircraft  nothing else happened. So we went and cleared the airspace on the way in then flew in circles for an hour doing nothing as the ground pounders did there thing

### Expected: 
 I have 2 suggestions, 

first make aircraft spawn out of the airspace and fly in to the AO

second, spawn enemies either when a objective is done or at random times during the mission (potentially when a player aircraft flys into a random area or something?$, or a mix of both. 

this will make it more interesting for the air cover, because at the moment we fly up, kill everything then burn back to base and rearm to switch rolls hahaha

**Comment by john681611** [comment]
Assuming you had a few aircraft spawn in the first wave. Then it sounds like your entire CAP quota was used up in the first wave. So this isn't a bug.

We don't want to make the missions `formulaic` by always having jets spawn once the objective is complete. I do like the idea of having a few other ways of having CAP spawn.

Distance to objective sounds like a decent idea as a way aircraft can spawn.

Time sounds like a good idea but it's very dependent on people playing at the right pace. We have a loop to spawn aircraft running at a set interval maybe we should randomize that from the 10s to maybe 5 mins.

I'll close this bug and create an enhancement ticket with a reference to this post
