### ISSUE TITLE
Bad Player Aircraft spawning (post all bad starting positions here)

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#262]
Ref: #254
### Brief Description: 
Aircraft can spawn in locations (usually bunkers) that are not suitable. Due to the number of positions, it's unrealistic to try and fix them in one go. So we are asking you to report any bad positions you find.

Format

```
Map -> Airbase -> positions on map  = position classification they should have.
```
Classifications:

- HelicopterOnly
- HardenedAirShelter (Assume must fit A-10 as largest playable aircraft)
- AirplaneOnly (In open-air but helos shouldn't spawn here)
- OpenAirSpawn,
_!Devs to make below this point!_
-  SmallHardenedAirShelter (smaller aircraft maybe max Mirrage TBD, small aircraft will need a flag on them)
-  Disabled

### Expected: 
Eventually, we don't have aircraft spawning in spots.

**Comment by PSYKO-nz** [comment]
Quick question  in regards to airfields, are all airfields on each map available to spawn at or is there a small number of fields that are use able?

also, the f14 should be the aircraft we use to judge size of hangars as the f14s wingspan unswept is 20m where the a10 only has an 18m wingspan. The tomcat is also taller than the a10. And while in the f14 I have had my height and/or wingspan get damaged or dragged along the walls/roof

Reason i ask is that I am happy to go through and check any airfields on the maps I have and find out what areas are ok for each field might take a week or so but I can do it :)

**Comment by john681611** [comment]
All airfields should be covered but if you want to be sure they exist then look into Database->TheatreAirfields. The problem is you can't do it in the editor as it has a hidden system that determines what aircraft can go in what and it's not the same as ours. 

That said if you can identify a bunker that is too small then find all of them on a map and report them then that's a significant improvement. As SmallHardenedAirShelter could be a be a bit of dev so it will probably be disabled internally for a bit until we can determine a `small aircraft`

**Comment by PSYKO-nz** [comment]
That’s the plan, if needed I can give you the parking space numbers for each airfield

however if I can just identify the bad hangers that will be faster and a bit easier, I’ll see what i can do, see if there’s a way to narrow it down to a class name if not I’ll just get the parking spot numbers at each airfield and send them to you, so you can see for yourself :)

**Comment by PSYKO-nz** [comment]
What is better for you,

a list of all good spaces on each airfield or a list of the bad hangars?

**Comment by john681611** [comment]
Bad spaces that need changing from a code point of view.
 We don't have access to map data to identify if a spot has a hanger or not let alone what type.

**Comment by PSYKO-nz** [comment]
Right, so I need to identify the bad hangar code it’s self rather than just a list of all the good/bad spots on each airfield

**Comment by john681611** [comment]
No, I need the positions as per format,
`Map -> Airbase -> positions on map  = position classification they should have.`
IE 
Caucuses -> Batumi -> 10,11 = SmallHardenedAirShelter 
This tells me I need to change Batumi airfield positions 10 and 11 to SmallHardenedAirShelter.

**Comment by PSYKO-nz** [comment]
Bugger, I was hoping I would just be able to grind through all airfields on a map finding the parking spots

**Comment by PSYKO-nz** [comment]
will this help at all?

https://forums.eagle.ru/topic/278957-how-to-find-a-specific-objects-classname/?tab=comments#comment-4743153

**Comment by john681611** [comment]
Probs not. This explains the crux of the problem well:
https://forums.eagle.ru/topic/193219-parking-spots/?do=findComment&comment=3700750

The dream would be to build a scraper to pull parking information including the size of the spot. Then we will need to configure the aircraft sizes but then we can use the same logic as ED uses in the ME to choose spots.

**Comment by PSYKO-nz** [comment]
So let’s see if I’ve got this.

I can’t just go and put a tomcat down on each airbase and record the numbers of the parks it will go in because the mission editor and the briefing room generator use different parking spot identifications? 

Also i can’t just find out what hangars are too small and record their classname’s because the BR generator also doesn’t use those classnames to generate spots?

the only way to find out the bad spots is to use the generator to create mission then record the bad spots?

I’m sorry, I’m not great with written words but I really want to help out. Once I understand what to do I’ll crack into it, please forgive my stupidity :)

**Comment by john681611** [comment]
Recent changes may help this by pulling data from ED

**Comment by john681611** [comment]
In a position where I don't think this will be a major issue.

**Comment by john681611** [comment]
Closing as Released
