### ISSUE TITLE
Ability to set radio frequencys and call signs of units

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#263]
### Brief Description: 
When me and my team make missions we use a standardised number of call signs and frequency’s, so that each time we fly we have better knowledge and their for SA about what is going on 

All units on a specific mission have the same call signs and all tankers or carriers or what ever are always on the game frequency’s and TACAN and so on. 

That way when we hear “colt 1-1 bandits braa” we know that the awacs is talking to the air to air formation. It also means when we need gas we know exactly what number to dial up.

it’s lifted our immersion because we don’t have to keep going back to the briefing page to see it, 

just a thought, it’s made our missions a bit more easy to maintain SA, might be a cool option for the future :)
 

### How does it work: 
 Maybe add a page to the UI with all the units there callsign, tail number and. frequency and tacan they use?

### Why can't it be done in the ME quickly: 
 It can be done in the editor but it takes time to find and change each unit and also, opening the files and changing things in the mission editor ruins immersion, because you’ve seen what’s coming!

**Comment by john681611** [comment]
So this is being able to set the callsign of the player flight group?

**Comment by PSYKO-nz** [comment]
And the friendly units as well, and the radio frequency’s for contacting them.

So we could set each flight of player aircraft callsigns 

but also, set the callsign and frequency for the awacs, tankers and carriers

**Comment by john681611** [comment]
Tbh to me, this is very much customisation that should be done in the ME.  Simply enough it's going to be quite a bit of work in the UI and backend for little value to most of our users who don't care about this stuff. 

We decided a while back that we would not support the requirements of those who want ultra-realism or those who be able to have fine control options. We would end up just making the ME. Hence why we do try and not break the ME with our missions. 

We do have an item in our plans to move a lot of the hardcoded stuff into a config file within the DB but it's a low priority.

**Comment by PSYKO-nz** [comment]
Totally understandable :)
