### ISSUE TITLE
FR : choose objective for each flight

### ISSUE THREAD

**Issue by davidp57** [akaAgar/briefing-room-for-dcs#270]
### Brief Description: 
Allow choosing an objective for the flights. That way we could have different flights with separate objectives (packages) in the same mission.
This is interesting for MP missions.

### How does it work: 
Add a dropdown in the "flight" parameters.
It displays the defined objectives, and a "random" option.
Use the selected objective as the flight objective.

### Why can't it be done in the ME quickly: 
We'd have to create whole flights in the ME

**Comment by john681611** [comment]
This is less about objectives per flight (something that is relatively complex) but we can have selectable waypoints and generate infil for each fight

**Comment by davidp57** [comment]
Hi John,
What do you mean by "generate infil" ?

On our side, we'd like to use BriefingRoom to generate multiplayer missions that we can play together on our server (btw "we" = the [VEAF](https://www.veaf.org/).

Usually, when we design a mission manually, we try and recreate what they do IRL : we create packages, each with an objective common to all its flights, but different from the other packages.

For example, we could have :
- PKG01 - Archer1 - a two-ships of A10-C running a CAP on the frontier
- PKG01 - Nitro1 - a patrol of F18 running TARCAP on the same frontier
- PKG02 - Striker1 - 4 M-2000C running a strike on a far away SAM site
- PKG02 - Astro1 - two F18 escorting Striker1
- PKG02 - Weasel1 - a pair of F18 running SEAD on the SAM site
This makes 2 packages, 5 different missions for 2 targets.

See what I mean ?

**Comment by john681611** [comment]
I get what you mean but the way the missions are generated is that the objectives are more or less independent of the flight groups.  The only thing linking them is the waypoints nearby. Even the briefing is still relatively general.

 Currently, we only generate 1 set of waypoints for all players that go to each objective and if the option is on adds infill and exfil waypoints.
 
 What I am proposing is being able to select which objectives each flight is going to do (default will be all objectives) and generate individual waypoint sets for each flight.  This brings a ton of exta complexity to how we do briefings but we need to sort that out anyway its not been right since carriers where added in.

**Comment by davidp57** [comment]
Sounds good !
Just one thing I didn't understand : the objectives waypoints are around the same objective, in what you propose ?
Meaning that, for one generated mission, there is one "objective zone" with different "activities" (CAP, strike, CAS) around there, and each activity has its own waypoints. 
Am I correct ?

**Comment by john681611** [comment]
Each objective has a waypoint. This waypoint may not be accurate as per the `inaccurate waypoint` option. There is no such thing as an objective zone.

Generally, I think the next big bit of work (apart from adding in mods) is to support the Co-op more by adding in more flexibility in how we match up objectives and flight groups. Currently, it's very single-player orientated.

**Comment by davidp57** [comment]
Ok, I understand.
It would be a great start, thank you !

**Comment by john681611** [comment]
I've been mulling this over and tbh the best method is to implement a `package` system ie a level above flight group it would be like this:

Package:
* Name
* Objectives (default all if one package) - Objectives probably need names now
* Flight Groups
* Starting Airbase (first package sets starting airbase Others have option of same, random or specific airbase)

**Comment by john681611** [comment]
Released Closing

**Comment by davidp57** [comment]
Thanks ! Can't wait to try this
