### ISSUE TITLE
Add label options 

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#274]
### Brief Description: 
 Let’s you set and enforce label settings on missions

### How does it work: 
Set the label settings for missions
Let you force things like dot only or neutral dot etc

### Why can't it be done in the ME quickly: 
 Because it would take longer to boot the editor up for one change

**Comment by john681611** [comment]
Honestly, it was enough of an issue stopping the app from enforcing a labeling system. I believe you can set up an enforced option on your dedicated server.

**Comment by PSYKO-nz** [comment]
Yes there is a way to do it on the server, I have it set up in my one. However it does not all ways work unfortunately.

**Comment by adamclmns** [comment]
Just looking and it seems this option is already in the UI, will test to see if it actually has the intended effect. 
![image](https://user-images.githubusercontent.com/1242662/136226673-272ed77d-e61e-4926-b494-50e91bd3cf9e.png)

**Comment by PSYKO-nz** [comment]
Would be good to have all options available,
Off
Dot
Neutral dot
Full
Etc etc 
During early days of briefing room I just pond up the mission file and manually changed the line that changed the labels, was just a matter of changing the number of one line if I remember rightly

**Comment by john681611** [comment]
You know there is a keybind to cycle this right?

**Comment by john681611** [comment]
The option can be changed here: https://github.com/akaAgar/briefing-room-for-dcs/blob/main/Include/Lua/Options.lua 
Usual warning about this basically being a mod to the code and be aware of overwrites

**Comment by PSYKO-nz** [comment]
So it's not possible to add in the option into the mission generator?

I will have to go back to editing the mission files then, thanks for the link for that too!

This was an issue last week where there were 4 of us testing the new version (working great by the way) and it wasn't until the end that we found out I have been using neutral dot while 2 of the others were using dot only and one had full labels, the one with full labels fully cleaned up haha, turns out it defaults to each players default label settings in there options, even tho I have it set up on the setting

**Comment by john681611** [comment]
Think you missed my point

In your BR install find `Include/Lua/Options/`  the label setting is in there.

Options are: 
None = 0
Full = 1
Abbreviate = 2
DotOnly = 3

This should force it but if you want to be sure add in on the line below:
`["setGlobal"] = true,`

No guarantees this will work.

I'm not saying it's not possible for the UI. But it has historically been a huge pain in the ass to get it not to force something we don't want in options and a significant bunch of code is missing to dynamically change the file so I'd rather avoid  it if possible
