### ISSUE TITLE
Enemy target/objective Units spawning out at sea.

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#275]
Latest of both

### Brief Description: 
 Mission target units spawning out at sea

### Expected: 
 Spawning on land

![41455269-2691-4073-8D85-28BFD02A90E0](https://user-images.githubusercontent.com/34756822/134604722-4291f2ba-3be0-4fbd-9eac-38a237ab7925.jpeg)
![107CD2CC-1828-441A-9574-4E91F01D715E](https://user-images.githubusercontent.com/34756822/134604786-aa154232-a33c-4efe-837a-0889256fef33.jpeg)
![EE30D2DB-6D7D-47D5-9344-64C1D92771EA](https://user-images.githubusercontent.com/34756822/134604808-5c21f4b4-2c09-465c-b168-dbee5edec38d.jpeg)
![8B25D84B-5519-4766-A7C0-264A2DDAF25B](https://user-images.githubusercontent.com/34756822/134604839-0f4413a7-7731-4776-a3a5-c49918d70ed2.jpeg)

**Comment by PSYKO-nz** [comment]
Will upload mission file soon

**Comment by john681611** [comment]
Yeah I'm gonna need to know what map this is on and the mission. Its in my todo list to create missions with all the waypoints on so we can debug stuff like this but that is going to be fun

**Comment by PSYKO-nz** [comment]
Sweet, here’s the file, had ment to upload sooner but got busy 

https://www.dropbox.com/s/simf32zhyjc7nqr/Syria%20-%20Operation%20Righteous%20Bullet.miz?dl=0

**Comment by john681611** [comment]
Released Closing
