### ISSUE TITLE
Adding JAS39C to aircraft list

### ISSUE THREAD

**Issue by whisky-actual** [akaAgar/briefing-room-for-dcs#276]
### Brief Description: 
 Could we please add the JAS39C (mod) to the aircraft list?

### How does it work: 
 Can be added as other un-official mods in the drop-down (https://github.com/whisky-actual/Community-JAS-39-C)

### Why can't it be done in the ME quickly: 
 Yes, I can change my flight quickly, but since all the ordinance is custom in our mod I need to re-arm every single plane every time and that becomes time-consuming.

I know this a lot of work, but will be greatly be appreciated!

Whisky

**Comment by john681611** [comment]
Sure can you help us out by providing a simple mission made in the ME with:

* Aircraft with a General loadout
* Aircraft with a SEAD loadout
* Aircraft with a Air To Air loadout

Also provide us with a list of liveries that come with the mod  (Folder names)

**Comment by john681611** [comment]
Released Closing

**Comment by whisky-actual** [comment]
Much appreciated mate!
