### ISSUE TITLE
Mission generation error - can't open a mission including ship objectives

### ISSUE THREAD

**Issue by FIVE-one51** [akaAgar/briefing-room-for-dcs#280]
### Brief Description: 
When creating a mission including ship as objectives, on the Marianas Island map, the game can't load it and gives the error (see screenshot)
It also messed up the mission editor to the point I couldn't open another mission and had to delete the user folder "MissionEditor" to get things right again.

### Expected: 
Usual mission generation

####  Example Mission File: 
![Screen_210930_172438](https://user-images.githubusercontent.com/54453987/135485994-b1347541-c028-4bfc-b8ea-473a69c3d9e3.png)

Mission modified: Y/N

**Comment by john681611** [comment]
We have seen this before please download the latest beta for fix.
