### ISSUE TITLE
AI Escorts

### ISSUE THREAD

**Issue by conorb69** [akaAgar/briefing-room-for-dcs#281]
**Brief Description:**

Is there any chance of re-introducing AI escorts for player flights? Fly with a package?

**How does it work:**

Allow user to create a full package in the Editor to allow AI CAP and SEAD escorts

**Why can't it be done in the ME quickly:**

Unsure

**Comment by john681611** [comment]
As stated this exists in terms of the taskable units. Due to MP actual escorting units may be harder to produce. For now, as a suitable alternative exists it's a low priority.

**Comment by john681611** [comment]
Closing due to core MP ED issue that we can't get the calling player from the F-10 menu means this isn't viable in MP. A suitable alternative currently exists too.
