### ISSUE TITLE
Unable to generate Air-to-Air Missions on Certain Maps

### ISSUE THREAD

**Issue by sncollie** [akaAgar/briefing-room-for-dcs#285]
### Brief Description: 
Cannot generate any Air-to-Air missions on certain maps.  Choose any aircraft type and press Generate, this error occurs:

"Error: Failed to spawn objective unit group. Air,LandSmall,LandMedium,LandLarge,Sea"

The error doesn't happen on Nevada, Normandy or The Channel...all other maps give me the above error.

### Expected: 
A mission should generate

No mission to attach.

**Comment by john681611** [comment]
Known and already fixed locally for me but pending other fixes before release.

**Comment by john681611** [comment]
Released Closing
