### ISSUE TITLE
Ground Spawn Air Units

### ISSUE THREAD

**Issue by ADiesel888** [akaAgar/briefing-room-for-dcs#286]
### Brief Description: 
Have support units spawn on ground. Instant spawning support aircraft will just take off. Hopefully tastable aircraft will be there and only be manned when spawned (not sure how it works) - John681611

### How does it work: 
 <John681611: - Can you create a ticket on GitHub for this. Probably just simply taskable and support aircraft start on ground>

### Why can't it be done in the ME quickly: 
 <it can be, just a pain having to edit a mission rather than jumping straight in and playing after generating a mission.>

**Comment by john681611** [comment]
Closing as Released
