### ISSUE TITLE
Not picking up kill/damage on static planes (in hanger)

### ISSUE THREAD

**Issue by Goofeyfoot** [akaAgar/briefing-room-for-dcs#293]
### Brief Description: 
 No Credit for Destroying Interceptors on Ground

### Expected: 
  I should have gotten credit for blowing up the mission interceptors which were in hangers.  I blew up both hangers and in fact the map shoed the interceptors as gone.  The JTAC also said their were no more targets to designate once I had blown up the interceptors.  Yet, I never got a "success" message" nor did I get a score credit on the debriefing.  So I think something is wrong.

####  Example Mission File:  nWe dont support that type of file .miz it says.  What?

Mission modified: Y/N Nn

**Comment by john681611** [comment]
Going to need some better wording here. Where are these interceptors that flew and landed or were they an objective target?

**Comment by Goofeyfoot** [comment]
The interceptors never flew. They were always parked in the hangers that I destroyed.

**Comment by Goofeyfoot** [comment]
The planes were targets kept in hangers. I destroyed the hangers and thereby, the planes.

**Comment by john681611** [comment]
Can you zip the mission file?
Just did a test with an open-air aircraft and it worked fine but tbf I hit it with 2 GBU-10's. We know the kill event isn't too reliable if it's a static aircraft. Maybe got reverted since we fixed the issue.

**Comment by john681611** [comment]
Probs need to re-implement this: https://github.com/akaAgar/briefing-room-for-dcs/blob/legacy-version-0-4-104-21/Include/Lua/IncludedScripts/ObjectiveMissionKill.lua

**Comment by Goofeyfoot** [comment]
As requested have zipped the file here.

[Syria - Operation Ravenous Fortune.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7574615/Syria.-.Operation.Ravenous.Fortune.zip)

**Comment by john681611** [comment]
Update on this:
* Fix: Airbase spawn listens to side limitations
* Fix: Airbase Parking spawn tasks waypoints are now on ground
* Added: Disable Task (better suited for attacking parked aircraft)

TODO:  Laser Objective feature doesn't detect unit has been knocked out.

**Comment by Goofeyfoot** [comment]
Man you don’t fool around! Good show.

**Comment by john681611** [comment]
Think I have laser designating solved. Not entirely sure yet.

**Comment by john681611** [comment]
Fixed in code will probably dump a new beta once odd looping bug in JTAC is fixed

**Comment by john681611** [comment]
Closing as Released
