### ISSUE TITLE
Airbase information is incorrect / changed.

### ISSUE THREAD

**Issue by VeeSPIKE** [akaAgar/briefing-room-for-dcs#294]
### Brief Description: 
I had a random mission start based out of Al-Maktoum airbase in the Persian Gulf. Flying an F5. I could not contact ATC on the channel supplied in the briefing, which was 251.10. Also of note: one of the other frequencies was wrong as well. The low frequency channel was briefed as 118.65. Which was also incorrect. 

### Expected: 
I checked with an airfield diagram I have and the channel was listed as 251.00. However, when I opened the Mission Editor to look up the airfield, the ME lists the correct channel as 251.20. Which makes me believe the ED has changed the frequencies for this a possibly other airfields. The ME also lists the correct low frequency channel as 118.60, but the briefing was for 118.65.

Attached - 1 miz and 1 html file - extensions changed for uploading purposes.

####  Example Mission File: 

Mission modified: Y/N Yes, mildly. But I did not do anything that would affect radios or comms.
[F5 - PersianGulf - Operation Safe Command.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7571772/F5.-.PersianGulf.-.Operation.Safe.Command.zip)
[F5 - PersianGulf - Operation Safe Command.txt](https://github.com/akaAgar/briefing-room-for-dcs/files/7571780/F5.-.PersianGulf.-.Operation.Safe.Command.txt)
->

**Comment by john681611** [comment]
Fixed in code
https://github.com/akaAgar/briefing-room-for-dcs/commit/8a59fcecbe56eb5b4fdcdd6f831e0c0a213cff5f

**Comment by john681611** [comment]
Closing as Released
