### ISSUE TITLE
Feature Request: Enemy AI Pilots Skill

### ISSUE THREAD

**Issue by lorthirk** [akaAgar/briefing-room-for-dcs#3]
Currently all Enemy AI aircrafts seem to be created with Rookie skill. It would be great if we could specify the skill when generating the mission instead.

**Comment by akaAgar** [comment]
Good idea, I'll add an option in the next version

**Comment by lorthirk** [comment]
Awesome, thank you!

Just a little suggestion, if I may: in open source devlopments, an issue should be closed only when it is actually addressed, so whoever reported it can know it has been fully worked.
