### ISSUE TITLE
Extra Waypoints not generating

### ISSUE THREAD

**Issue by CallsignScooter** [akaAgar/briefing-room-for-dcs#306]
### Brief Description: 
 
Selecting extra waypoints option for ingress and egress are not generating in campaign missions.

### Expected: 
 
At least 2 additional waypoints for each generated mission.

#### Mission and Template Zip: N/A 

Mission modified: Y/N  N

**Comment by john681611** [comment]
Cause Found basically features wasn't getting assigned to individual missions. Fixed in code out next beta.

**Comment by john681611** [comment]
Closing as Released
