### ISSUE TITLE
Select Airbase in Campaign Generator

### ISSUE THREAD

**Issue by CallsignScooter** [akaAgar/briefing-room-for-dcs#307]
### Brief Description: 
 
Being able to select home airbase on campaign generation.
### How does it work: 
 
A dropdown menu in the Context tab to select an airbase to take off from on each mission and to leave blank for a random airbase.
### Why can't it be done in the ME quickly: 
 
Depending on how many units are spawned in the package and objective placements, it would take a while to adjust all the units on each individual mission to accomplish this.

**Comment by john681611** [comment]
Campaign has had a general refresh should be much more up to date and include this feature.

**Comment by john681611** [comment]
Closing as Released
