### ISSUE TITLE
situation change randomly on mariana theater

### ISSUE THREAD

**Issue by Anthon355** [akaAgar/briefing-room-for-dcs#325]
### Brief Description: 
Only on mariannas theater, when we choose any "island hoping" or "retake the island" situation, the situation change randomly when we click on generate button (situation change on briefing mission on the right)

### Expected: 
Normaly, the situation have to stay like choose on context

#### Mission and Template Zip: default template

Mission modified: N

**Comment by john681611** [comment]
Fixed in code.

**Comment by john681611** [comment]
Closing as Released
