### ISSUE TITLE
Mission Script Error after JTAC lasing kill

### ISSUE THREAD

**Issue by olympian-mods** [akaAgar/briefing-room-for-dcs#326]
### Brief Description: 
1. Ask JTAC to lase mobile ground target, e.g. Tank (Radio menu "F10 Other")
2. In F/A-18C launch GBU-12 on lased target
3. As soon as target is killed DCS freezes and shows error window "Mission Script Error"
4. Error window can be closed and DCS will continue to work

![2021-12-22 18_13_53-Mission script error](https://user-images.githubusercontent.com/20711141/147334149-ab77b2a4-7ad6-4a24-a568-6456cbda9ac9.png)
(Referenced LUA script `~mis0000734D.lua` is attached below)

### Expected: 
No error should appear after killing ground target that has been lased by JTAC.
The error seems to happen because of line 984 in Briefing Room's `~mis0000734D.lua` that looks like this:
```lua
if not table.contains(objective.unitsID, tonumber(objFeature.targetDesignationLaser.laserTarget:getID())) then -- target is considered complete
```

#### Mission and Template Zip:
* [~mis0000734D.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7773414/mis0000734D.zip)
* [Caucasus - Operation Immediate Fire.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7773416/Caucasus.-.Operation.Immediate.Fire.zip)

Mission modified: Y. Modified very slightly (repositioning of some units and deletion of some SAMs).

**Comment by john681611** [comment]
Was just about to report this thanks for the excellent report

**Comment by john681611** [comment]
Closing as Released
