### ISSUE TITLE
Feature: Carrier Ops

### ISSUE THREAD

**Issue by Rumcajsev** [akaAgar/briefing-room-for-dcs#33]
It would be great to have an option to start the mission on a carrier, if the selected aircraft allows for this.

Additionally this would be a cool mission objective - fleet defence, where player needs to defend the carrier they started on from enemy attack.

**Comment by john681611** [comment]
Carrier ops are coming soon TM
As well as an intercept variant that attacks the players starting ground base (carriers spawn separately) 
`
Me and @akaAgar were chatting about supporting AI attacking a variety of infrastructure in the future (other bases, FOBs, etc) ships and carriers could be added to that list

**Comment by john681611** [comment]
Released

**Comment by Rumcajsev** [comment]
Closing, since it was implemented in version 0.3.101.20
