### ISSUE TITLE
Adding USA Aggressor coalition

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#335]
### Brief Description: 
Can you please add the USA coalition. 

### How does it work: 
DCS does have a USA aggressor coalition  located in add or change coalitions

### Why can't it be done in the ME quickly: 
 Changing it in the ME would be time consuming

**Comment by john681611** [comment]
Done in code. Note BR chosen coalitions don't show in-game coalitions. This also needs to be fixed

**Comment by john681611** [comment]
Closing as Released
