### ISSUE TITLE
Templates not saving 

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#336]
### Brief Description: 
 Templates are not saving

### Expected: 
 Selecting Save will only save in text file and no other file type. 

#### Mission and Template Zip: NA

Mission modified: Y/N No

**Comment by john681611** [comment]
It says Text Document but will provide the default file type of .brt as windows don't understand its different.
if you do accidentally save it in the wrong type then just changing the ending to .brt works fine.
