### ISSUE TITLE
Strike Packages waypoints don't work with SubObjectives

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#340]
### Brief Description: 
 Seems that adding multiply Players or aircraft inside mission briefing UI. will not assign package flight a target.

### Expected: 
Each package created should be able to have its own target when selecting generate.  Attached is the brt file. Just generate a mission and you may see what I'm talking about. 

#### Mission and Template Zip: Dragging a Zip flie here does not work

Mission modified: Y/N n

**Comment by john681611** [comment]
Can you please be super clear with your issue screenshots and the like? I'm not really sure what the issue you are reporting is.

**Comment by Wood-VCW3** [comment]
Ok after sitting here trying to make it work I found out this. Using Complete mission builder if you have multiple players and assign them each there own objective it simply doesn't work. The aircraft listed last is the only group that will be assigned targets. 
Now using Quick mission and again inserting multiple Players, again you can't give them their own objective. Each flight will have the same targets. Example
A pair of F-16 assigned with an object for SEAD
a pair of hornets off the carrier assigned naval targets (Anti-Ship)
A pair of A-10's Assigned interdiction Ground attack
All will have the same targets in their respective flight plans. 
Don't need an A-10 doing a anti ship strike a 100 miles out. and same with the F-16. 

This is only good for one flight I'm afraid. Can't make complex missions with this.

**Comment by john681611** [comment]
Ok I think I get you now. Updated the title

**Comment by john681611** [comment]
Closing as Released
