### ISSUE TITLE
Refactor Briefing Descriptions

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#352]
### Brief Description: 
Our Main Briefing descriptions are poor and only represent the first objective. Now we can have multiple strikes and objectives we have to write something better.

### How does it work: 
Not sure yet

### Why can't it be done in the ME quickly: 
N/A

**Comment by Wood-VCW3** [comment]
The Briefing layout were nice and much clear on the old briefing room when it was HQ4DCS

**Comment by john681611** [comment]
Yup no denying that. Making a ticket to refresh the briefing layout. We can probably cut a bunch of stuff or hide it behind an extended briefing feature

**Comment by Wood-VCW3** [comment]
I hate to say it because I know that its totally different but if the briefing card could mimic what Liberations has would be great.
