### ISSUE TITLE
Error: Countries can't be on both sides CJTFBlue

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#353]
### Brief Description: 
Generating a Red flag mission using USA as BLUE FORCES and USA AGRESASORS as RED FORCES. Generating the mission will have a error message indicating "Error: Countries can't be on both sides CJTFBlue"
Only when you switch to forces to opposite sides will it generated the mission. 

2nd. Have a look at the .BRT file and the mission it generated. Aggressor and blue force show only as blue. 

### Expected: 
USA Aggressors forces should be Hostile. 

#### Mission and Template Zip: 
[RED Flag Senerion Blue wrong side.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7921541/RED.Flag.Senerion.Blue.wrong.side.zip)

Mission modified: Y/N

**Comment by john681611** [comment]
Ah problem is caused by hostile aircraft not auto switching to CJTFRed

**Comment by john681611** [comment]
Ok true cause was: Player aircraft didn't have a sense check if  you tried to spawn a CJTF aircraft on Red side or visa versa. This led to a bunch of issues worst was if you just set to red coalition your player aircraft could still be on blue side.

Fix: correct CJTF sides just before generation and make change to template.
