### ISSUE TITLE
All aircraft have no loadouts when generating a mission

### ISSUE THREAD

**Issue by isotaan** [akaAgar/briefing-room-for-dcs#356]
### Brief Description: 

Created a combat air patrol mission, both under the Quick Mission Builder and under the Full Mission Builder. Both methods of creating the mission ended up with all aircraft (player and AI) having empty loadouts.

### Expected: 

Aircraft should have had loadouts. Under the Full Mission Builder there's even an option for the loadout for the player's aircraft.

#### Mission and Template Zip: <!-- Drag and drop a zip of your template (.brt) file and an example mission file (.miz) here. So we can 

[Missions.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7921842/Missions.zip)

Mission modified: N

**Comment by john681611** [comment]
Realised this Hotfix coming out soon!

**Comment by john681611** [comment]
Closing as its now fixed and released
