### ISSUE TITLE
Amphibious vehicles keep going out to sea on patrol

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#364]
#### BR Version: last 3 up to stable.

We have over the last 3 weeks had every single mission with "patrolling" vehicles heading out to see for a spot of fishing, units seem to always head out to sea, and because they go so slow in the water they never end up back on land, they are normally out at sea by the time we get to the AO, so either they are spawning on land then heading out or they are spawning at sea, doesn't seem to matter what map or BR version

**Comment by john681611** [comment]
Gonna need an example mission and template

**Comment by PSYKO-nz** [comment]
Sweet, I'll get that to you hopefully tomorrow :)

**Comment by john681611** [comment]
still waiting on an example mission and template here. I'll close if we don't get the info.

**Comment by PSYKO-nz** [comment]
Hey mate, please don't close I just haven't had time to go back through the missions I have saved to find the ones with the issue, aiming for this week to get them through

**Comment by john681611** [comment]
Ok I was going to give it a week so anyway.

**Comment by PSYKO-nz** [comment]
I will be playing a mission tonight and a few times over the next week to get fresh versions of this issue, the ones I had are about a month old now and not useful for the bug,

can you please keep this issue open for a few more weeks and I’ll upload any mission that I find with the same issue over the next few weeks 

sorry to be a pain! 

I will try post up some of the older ones too

**Comment by john681611** [comment]
Think this may be solved so closing now
