### ISSUE TITLE
BR missions crashing servers/not spawning opfor

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#366]
as per discord discussions...

BR missions currently crash the server or when it does load it does not load any opfor unit

mission files attached
[missions.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/7962418/missions.zip)
s

**Comment by john681611** [comment]
Issue must be newer than beta-release-211231-1712

**Comment by john681611** [comment]
Break somewhere in this diff: https://github.com/akaAgar/briefing-room-for-dcs/compare/beta-release-220110-2001...beta-release-220114-2101

**Comment by john681611** [comment]
Ok pretty sure it was us trying to be neat and not include a country in the mission code if It didn't have any units in.
