### ISSUE TITLE
Lead is been designated as number 2

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#372]
### Brief Description: 
A couple of things. 
1. After creating a mission whether its a QM or full mission, The flight lead will be designated as number 2. Example I take a lead slot and call ATC the callsign will be followed by 22 or 12 or 32. never 11, 21 or 31. 

2. I've noticed the radio frequencies are not been updated it the mission to the base of operations to Awacs.  

### Expected: 
Should be registering as position. This has been noticed for the last few updates. 

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment]
> After creating a mission whether its a QM or full mission, The flight lead will be designated as number 2. Example I take a lead slot and call ATC the callsign will be followed by 22 or 12 or 32. never 11, 21 or 31.
 Fixed

> I've noticed the radio frequencies are not been updated it the mission to the base of operations to Awacs
This is a separate enhancement please create a separate issue for this.

**Comment by VCW3-admin** [comment]
That’s for the quick fix. I’ll post a separate post for the frequencies.
