### ISSUE TITLE
Assigning Aircraft to specific bases in Quick mission 

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#373]
### Brief Description: 
Is there a way to have the ability to select your airbase in the Quick mission instead of BR selecting it for you. 

### How does it work: 
The QM will generate your flight out of Civilian airports and not give the ability to change it. 

### Why can't it be done in the ME quickly: 
 Difficult to change in ME and pointless

**Comment by john681611** [comment]
Generally, I think that the Quick mission editor has got enough options. Frankly, the Full editor is feeling borderline too much. 

Remembering the aim of the full editor is to take a few minutes to configure a mission that would take much longer to make. The Quick editor is designed around being even faster by using a full editor template  - "more of the same kinda stuff please"

The QMB UI needs to make that clear.
Its also fair to say the QMB needs to handle full templates better.

**Comment by VCW3-admin** [comment]
So just tone clear, the full mission template can be used for Buick mission builds. Is that correct assumption that should be tested?

**Comment by john681611** [comment]
Yes

**Comment by Wood-VCW3** [comment]
Actually, I like using the full mission Template for Quick mission use. So far looking good.

**Comment by john681611** [comment]
I added Home base the more I thought about it the more I realised you were right.
Below is the indications to help people understand the link
![image](https://user-images.githubusercontent.com/10814889/152674870-964d1cc2-49a8-4e83-a27a-0bad230476ed.png)
![image](https://user-images.githubusercontent.com/10814889/152674875-bcdc4ffa-36ca-4320-9231-3aa2885e1665.png)
![image](https://user-images.githubusercontent.com/10814889/152674882-70296316-6772-4634-8213-eb7c7e3eed68.png)
