### ISSUE TITLE
Request to change AI wingman communication to VHF radio. 

### ISSUE THREAD

**Issue by VCW3-admin** [akaAgar/briefing-room-for-dcs#376]
### Brief Description: 
 Not sure why this was implemented this way but, AI aircraft such as wingman should be utilized on comm two. It seems that in DCS frequencies with ATC, AWACS and Tankers are always giving reference to and using UHF frequencies. If you switch to AWACS or Tanker on UHF you can no longer communicated with the wingman because it using UHF frequencies. (Note: ok with aircraft such as the F18 or aircraft that can use ether radio as UHF or VFH but aircraft such as the F-16 is useless as each radio is either UHF or VHF.). 
 

### How does it work: 
 I’m not sure if this is a DCS limitation or what because if I’m not mistaken Liberation did  the exact same thing at one time but I believe that changed.  Maybe someone can confirm that if they flown Liberation recently. 

### Why can't it be done in the ME quickly: 
 This can be changed in the ME but defeats the purpose of the utilization of the BR.

**Comment by john681611** [comment]
ref comment on #375. But I guess this is more possible as it's not aircraft specific,

**Comment by john681611** [comment]
Default Unit radios were not all the same. Changed them so there was some kind of pattern
![image](https://user-images.githubusercontent.com/10814889/152656977-a1789ad9-bf02-47fe-8403-315f9da56d9e.png)
Generally, 
- Fighters are on 124.0
- Drones 130.0
- Bomber/Transport 129.0
- Helicopters 128.0

Hopefully this is much better

**Comment by Wood-VCW3** [comment]
That's a good idea. Looking forward to checking it out.

**Comment by Wood-VCW3** [comment]
Just a quick note. The frequencies changes you implemented are not working. Attached is a briefing indicating the frequencies as you indicate in the previous post and showing on the briefing are correct. However, not the case in the mission. 
This mission was created from a full mission template and generated in Quick mission builder.
[Syria - A-10II Operation Unchained Junction.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/8051342/Syria.-.A-10II.Operation.Unchained.Junction.zip)
You'll also note a couple of other issues such as HATMAN waypoint was not created for the two flights. Spent a fricken hour looking for the targets and my own stupidity. lol I'll create another bug for this issue as it has nothing to do with the frequency problem
