### ISSUE TITLE
Waypoint generation. 

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#378]
### Brief Description: 
Generating this quick mission which is attached from a full mission template you can see an issue where the target waypoint was not generated. Also the Waypoints are been generated at altitudes of 15000' ft when the they should be ground based. 
Another bug noted which I'll post separately. 
The Task feature also has illumination bomb and designated smoke marker which does not work. I could only get coordinates. 

### Expected: 
 Way points should be added and at ground base.  

#### Mission and Template Zip: 

Mission modified: Y/N No
[Syria - A-10II Operation Unchained Junction.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/8051396/Syria.-.A-10II.Operation.Unchained.Junction.zip)
>

**Comment by john681611** [comment]
@Wood-VCW3 can ou test this again in latest beta?
