### ISSUE TITLE
Objective Features not working from quick editor

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#379]
beta-release-220207-0002, DCS 2.7.10.19473 Open Beta hotfix

### Brief Description: 
The Objective feature also has an illumination bomb and designated smoke marker which does not work. when generated from the quick editor using a full template. I could only get coordinates. Not sure if anyone else is noticed this Task feature. 

### Expected: 
Should not everyone selected be available?

#### Mission and Template Zip: The mission has been loaded in the previous bug reports. 

Mission modified: Y/N

**Comment by john681611** [comment]
Think we need a bit more information on this issue.

**Comment by john681611** [comment]
Ok updating title and description to be more useful but I'll give it a look

**Comment by john681611** [comment]
@Wood-VCW3  can you re-test this with latest beta?

**Comment by john681611** [comment]
Heard nothing for a while closing
