### ISSUE TITLE
CAS and CAP Mission Loadouts???

### ISSUE THREAD

**Issue by Jeffb4u** [akaAgar/briefing-room-for-dcs#397]
OK sorry dumped all that - Problem im having is F16 CAP missions places a CAS Loadout on - Created 2 CAP missions and the bird had 4 GBU12's and a TPOD - Edited several times - Actually took off on one and killed a Mig31 - Mission flagged me as complete RTB - Im still hanging in the air with 4 GBU12's so yeah seems not to know CAS/CAP in F16 maybe.

Im going to add a feature wish but hey man please dropped the EYE GOUGING WHITE for a pale blue/grey or something my eyes are still watering here

**Comment by john681611** [comment]
Please follow the template given to you for bugs. It seems you selected the General loadout in the flight group UI which is a mix choose the air to air loadout for better suitability.
