### ISSUE TITLE
spawn issue, some of the target aircraft died as soon as they spawned

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#402]
had a weird spawn issue, some of the target aircraft died as soon as they spawned, not sure what happened, here's the mission
[Syria - Operation Unrelenting Junction.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/8260452/Syria.-.Operation.Unrelenting.Junction.zip)

**Comment by john681611** [comment]
Units spawn fine for me in testing but they have no waypoint so they land and de-spawn (ED thing for some reason) Can't really do much here so closing.
