### ISSUE TITLE
Units spawning in or driving into water some become invulnerable, files and videos included

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#415]
### Brief Description: 
 Finally got round to finding the issue previously reported

Units are spawning either in the water.or spawning on land and then driving into the water.

Once they are in the water they become very hard to hit because it's DCS and anphibous stuff isn't well moddled, but it also seems that the units become invulnerable when they are on the shoreline

On the Marianas mission we put an ungodly number of rockets, 20mm and at least 4 GBU24s onto a truck spawned on the shoreline in a cove and it just would not die, on the Syria one we killed a lot of units but there were a few on the shoreline or close to in the water that were on godmode, and on those, we'll watch the videos to see what we did...

### Expected: 
 Stop all units from going into the water. It's buggy as with in DCS at the moment, if possible just prevent the units going near the shoreline and into the water and the issue should go away

#### Mission and Template Zip:

Both missions are in the zip and are un modified, I generated them in the full mission builder mode using the standard settings I have used without issue for a while now

[br issues.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/8495034/br.issues.zip)

First video,

https://youtu.be/Ay5QMf5NaZo

Second video, this took place AFTER the attack in the first video

https://youtu.be/U9y9jV_Fo3E

As you can see they are definitely not dieing lol

**Comment by john681611** [comment]
Vehicle unit spread reduced from 200m to 100m meaning costal vehicles should be less likely to spawn in the water.
The two indicated points on Marianas have been removed. Please test on latest beta.
