### ISSUE TITLE
Cannot open WW2 asset even if I have downloaded

### ISSUE THREAD

**Issue by Jacke1012** [akaAgar/briefing-room-for-dcs#417]
### Brief Description: 
It says i am missing modules

### Expected: 
 It should load because I have the modules

![image](https://user-images.githubusercontent.com/46431999/164044281-8a073166-25cc-425e-bfdf-0f6c5c100c13.png)

![image](https://user-images.githubusercontent.com/46431999/164044298-7b678c37-2329-490a-b1fc-9fc2c0421880.png)

![image](https://user-images.githubusercontent.com/46431999/164044325-908188bb-42ff-4035-ab3e-274544ccb0d0.png)
This last one is how an empty mission with the JU-88 and flak placed. As you see it says WW2 required not JU-88 etc.
![image](https://user-images.githubusercontent.com/46431999/164045119-a44576b9-f2c4-4f90-9f84-0e7aea420751.png)
This is the random.miz to prove that the JU-88 works with my game

#### Mission and Template Zip: 
[Template and mission1.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/8514553/Template.and.mission1.zip)

**Comment by john681611** [comment]
Ah I haven't got the ID for WW2 stuff (I don't own it) can you quickly make a mission with a ww2 units and send me it.

**Comment by Jacke1012** [comment]
Nice. Thanks dude
