### ISSUE TITLE
Voice only objective messages

### ISSUE THREAD

**Issue by Lancer68** [akaAgar/briefing-room-for-dcs#468]
### Brief Description: 
Provide an option for mission objectives notifications (example "Good hit on target") to be given through radio voice only and not an on-screen message.
 
 This would allow the screen to remain clean of messages which would provide a more immersive view.
 This would fall in line with the reasoning of not having chat or battle damage reports display on the screen.

**Comment by john681611** [comment]
So this is definitely doable but it comes with some downsides apart from the obvious intention. There are certain radio messages where the sound is generic but the information conveyed in the text is custom. If this is to be truly voiced only then these messages which may contain critical info such as coordinates or laser codes will disappear. I could make it so only non-critical info is voice only but that breaks the "immersion" value of this feature.

**Comment by john681611** [comment]
Closing for reason posted long ago
