### ISSUE TITLE
Syria map support

### ISSUE THREAD

**Issue by WackoZA** [akaAgar/briefing-room-for-dcs#47]
Hi guys, I cant seem to get this to work for Syria, has support been implemented yet or not?

**Comment by akaAgar** [comment]
Beta support, with a limited number of unit spawn points, has been implemented in the current code, it will be available in the next release (coming this week)

**Comment by WackoZA** [comment]
Hi @akaAgar many thanks  for the prompt reply. looking forward to the syria support. such a great tool this, thanks man. really got worried after HQ stopped developing :D
