### ISSUE TITLE
Custom built in-game loadouts aren't available to select in Briefing Room beta

### ISSUE THREAD

**Issue by gkleinfe** [akaAgar/briefing-room-for-dcs#489]
### Brief Description: 
 I created a loadout in-game for the F18, but it's not available as a payload in the flight group when F/A-18C Hornet is selected.

### Expected: 
 I expect to see loadouts for the F18 in Briefing Room after creating a custom loadout in game.  The latest stable release provides this functionality, but it appears not to work in the beta.

**Comment by john681611** [comment]
If you load the web version of the tool up please see if the incompatibility warning comes up for the F/A-18C.  If so this indicates that the tool can't read the loadout file. This is normally due to a loadout name breaking our code. I'm trying to find the example of the last one we confirmed that broke the logic.

**Comment by john681611** [comment]
Its usually the usage of `:` with a number preceding it

**Comment by gkleinfe** [comment]
Here are screenshots from the Beta web, Beta app and the stable 0.5.206.22 app.  Only the stable app yields the expected result
![App Version Beta](https://user-images.githubusercontent.com/3876224/183187242-5fed6c08-19de-4bdf-89be-9c03633616d2.png)
![App Version Stable 0 5 206 22](https://user-images.githubusercontent.com/3876224/183187280-f336b5dc-7e2c-491d-a636-7b00f0064abb.png)
![Web Version Beta](https://user-images.githubusercontent.com/3876224/183187298-b655f618-b123-4fe8-835c-716a9f81fc0e.png)
.

**Comment by john681611** [comment]
hmm and anything from the console logs of the webserver?

**Comment by gkleinfe** [comment]
Doesn't look like anything is logged unless I'm looking in the wrong place.
![BR Web Console](https://user-images.githubusercontent.com/3876224/183248957-24882cf5-6751-49de-972d-48834f72d6db.png)

**Comment by gkleinfe** [comment]
Adding to this, I saved a custom loadout for the A-4E-C and was able to see it in both the stable and beta releases.  Furthermore, I cleared the custom loadouts for the F18 and created a new on and now I can't see that one in either release.

Could the "/" in F/A-18C hornet be causing a problem?  The files name in MissionsEditor/UnitPayloads for the F18 is FA-18C_hornet.lua.

**Comment by john681611** [comment]
hmm maybe they changed the name I've been rather busy with other work and ideas but I'll give mine a check now

**Comment by john681611** [comment]
Figured it! https://github.com/akaAgar/briefing-room-for-dcs/commit/5f868cf49b2ec6f6c53119069de57a033d170fdf
Basically ED fixed the hornet using a custom loadout name. Just go into `Database\Units\PlaneFighter\FA-18C_hornet.ini` and remove the DCSPayloadName line

**Comment by gkleinfe** [comment]
That worked.  That'll help a lot setting up missions.
