### ISSUE TITLE
Folder dialog retain previous selection and open file name

### ISSUE THREAD

**Issue by gkleinfe** [akaAgar/briefing-room-for-dcs#490]
It would be nice to retain the last folder for each of the types of files that are opened.  Specifically, store the Template Load/Save folder, the mission download folder and the briefing download folder all separately.  I keep my templates in a folder, missions in my Saved Games/Mission folder and store the briefing html in a folder on a web server.

I'd also like to see the file name of the template retained temporarily so when I click Save, its auto populated.

The reason, I'm lazy saving templates, and the template saves to Default each time.  If I open a custom template, I could click on Save (Template) then simply click Save rather than having to scroll down and file the file or typing the file name.

As for paths, if I could either predefine the paths or if they were individually retained, when I generate a mission, I could click (download) Mission, Save then (download) Briefing then Save, and the files would be where they are needed automatically without having to browse around to the save locations.  And, keep the path separate from the template operations.

**Comment by john681611** [comment]
You may be interested in the hidden feature that you can actually load missions up. If you haven't manually edited the mission it will have a copy of the template that was used to generate it inside of it.
