### ISSUE TITLE
F14 start with LAU-138 filled with chaff

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#50]
hi there, I'm not sure if this is the right place to post, I looked for a DCS forums page but couldn't find one. at any rate can you please set it up so that the f14b in both sp and mp loads with the LAU-138 filled with chaff, at the moment it does not spawn with them loaded with chaff which means you have none to use leaving you completely reliant on maneuvering alone to trash missiles. having chaff would be much easier. again sorry if this is the wrong place to post.

**Comment by john681611** [comment]
You can re-arm before taking off the mission and for now, you can so go into the editor and correct the mission manually.

I'm not sure how this works so if you can send an example mission file with just an F-14 properly counter measured I'll get a fix in.

**Comment by PSYKO-nz** [comment]
Sweet, at this stage going into the editor will be the only way to do it, as it has to be added to the aircraft in the aircraft options when it’s placed, currently the flair/chaff bars don’t do anything, it’s all in the setup.

mill flick through a mission and a screenshot soon :)

**Comment by PSYKO-nz** [comment]
![Screen_210123_140515](https://user-images.githubusercontent.com/34756822/105563849-7d0cf700-5d84-11eb-8727-ade954c4947d.png)
the red arrow in the screenshot shows the option that needs to be checked, also note the one above it (an/ale39 loadout) shows how the onboard chaff and flairs are set up, the faders in the rearm window do not affect the loadout at all, it's all done here. 60 flairs + fill LAU-138 with chaff is the ideal loadout for countermeasures on the cat

here's the mission file...
[cat setup mission.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5859369/cat.setup.mission.zip)

Just a quick note as well, if you check 'INS Reference Alignment Stored' the ins alignment on start will be much shorter, as all the ins stuff is already on the aircraft, will help with cold start missions (i forgot to check this in the screenshot but fixed it in the mission file)

**Comment by john681611** [comment]
Thanks will have a quick look today

**Comment by akaAgar** [comment]
I guess the F-14 must use some custom Lua code for its countermeasures. I'll add an "ExtraLua" line in the units .ini files, which will allow the insertion of the custom Lua code required by some units (I think the F-16 needs some exotic Lua value for its fixed laser code too, but maybe it changed, I haven't flown it it some time). That should be quick, I'll do it this weekend.

**Comment by john681611** [comment]
`["LGB100"] = 6,
                                            ["M61BURST"] = 0,
                                            ["IlsChannel"] = 1,
                                            ["LGB1"] = 8,
                                            ["KY28Key"] = 1,
                                            ["TacanBand"] = 0,
                                            ["TacanChannel"] = 0,
                                            ["LGB1000"] = 1,
                                            ["LGB10"] = 8,
                                            ["INSAlignmentStored"] = true,
                                            ["UseLAU138"] = true,
                                            ["ALE39Loadout"] = 0,
`

**Comment by john681611** [comment]
#53

**Comment by akaAgar** [comment]
Done!
