### ISSUE TITLE
Adding 'Ships' in options causes error on South Atlantic map

### ISSUE THREAD

**Issue by bwanaaa** [akaAgar/briefing-room-for-dcs#501]
### Brief Description: 
In Full mission generator, choose South Atlantic Theater.
Choose home airbase Punta Arenas.
Add two F18C aircraft to the George Washington, then

Clicking on 'Ships' in mission features for enemy , then 'generate' causes error:
Warning: No spawn point found for mission feature EnemySea.

OR

Clicking on 'Ships' in mission features for friendly , then 'generate' causes error:
Warning: No spawn point found for mission feature FriendlySea.

### Expected: 
generate a mission without error
[SteadyWarden.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/9438853/SteadyWarden.zip)

#### Mission and Template Zip: 

Mission modified: Y/N NO

**Comment by john681611** [comment]
This was due to situations where the search radius for mission features would max out at approx 100nm this has been doubled to 200nm and it seems to mitigate it as an issue,
