### ISSUE TITLE
Select conflict zone

### ISSUE THREAD

**Issue by bwanaaa** [akaAgar/briefing-room-for-dcs#502]
### Brief Description: 
Select front line location on map

### How does it work: 
Allow the user to type a set of coords where the conflicting units will center around. Or to make it even easier, present a map and allow the user to drag a crosshair to a location

### Why can't it be done in the ME quickly: 
Changing a conflict zone requires moving the innumerable troops that Briefing room deposits on a map. Presently, If I select conflict for Argentina and Chile on the dropdown for the SouthAtlantic map, It always puts the conflict at the same location on the border, even thouygh there are numerous places to stage a conflict. Mountains for example.

**Comment by john681611** [comment]
I've had this idea recently to abuse the map tech we currently have. The problem is translating the fairly low res map coordinates to in-game coordiantes

**Comment by bwanaaa** [comment]
Maybe just start several regions that you have predefined for each conflict. For example, Chile vs Argentina could have another drop down allowing selections like ‘in the mountains,on a river, east, west,etc

**Comment by john681611** [comment]
That method would require configuration on maps and as I don't own everything it usually ends up more complex.

**Comment by bwanaaa** [comment]
I noticed you made some updates to the code. How do I compile this for windows? I do not see an .sln file or any indication that you used visual studio.

**Comment by john681611** [comment]
> I noticed you made some updates to the code. How do I compile this for windows? I do not see an .sln file or any indication that you used visual studio. I can't imagine how to compile all the files of such a project from the command line.

Think this chat is best made on our discord

**Comment by john681611** [comment]
Could be part of #543

**Comment by john681611** [comment]
You can now hint the area to be played and use the situation editor to create your own situation
