### ISSUE TITLE
Add DATIS support

### ISSUE THREAD

**Issue by wrycu** [akaAgar/briefing-room-for-dcs#505]
### Brief Description: 
Add support for [DATIS](https://github.com/rkusa/DATIS), which provides weather information over SRS.

### How does it work: 
Toggle "add DATIS objects" or "enable ATIS", Optionally allow custom frequencies.

### Why can't it be done in the ME quickly: 
Requires figuring out the naming scheme of various airports, renaming things, etc. Since we have random weather, it'd be awesome to also have something reporting the weather.

**Comment by john681611** [comment]
Looking into this it requires a good amount of work for the value.  Though it is a feature I'd quite like to see in EDs re-done ATC (though that is wishing)

**Comment by john681611** [comment]
I'm going to close this in preference for the moose implementation that doesn't use SRS and is generally easier to implement
