### ISSUE TITLE
Designation: Illumination bomb and Designation: Launch Flare don't work

### ISSUE THREAD

**Issue by Juanillus** [akaAgar/briefing-room-for-dcs#525]
Designation: Illumination bomb and Designation: Launch Flare options don't work. I think the problem is in the .lua files TargetDesignationIlluminationBomb.lua and TargetDesignationFlare.lua. 

Designation with smoke, TargetDesignationSmokeMarker.lua works fine.

**Comment by john681611** [comment]
Can you give me a description of how it fails?

**Comment by Juanillus** [comment]
Selecting the option via F10 menu just plays the first ogg audio "Request illumination bomb" / "Request flare marker" and then nothing happens. Don't know if there is a syntax error in lines 34&37 in both luas: "local args = { ["position"] = unit:getPoint() }", or is something else. Just trying to help, I know nothing about lua programming.

**Comment by john681611** [comment]
I think I've figured out why. There is literally no code for creating the flair/illumination bomb!

**Comment by Juanillus** [comment]
Downloaded the last beta and works fine, congrats and thank you. This is a very useful tool.
