### ISSUE TITLE
Option to add AI flights to a MP mission

### ISSUE THREAD

**Issue by Valk77** [akaAgar/briefing-room-for-dcs#56]
I would be nice to have the option to create a MP mission where you can select what slots are for clients and what slots are going to be flown by AI.
Now if there are only two human players you can't create a package with addtional AI CAP and SEAD escort flights (or at least not that I'm aware of) or a package where one player leads the objectives flight and the other player leads the SEAD flighs and the other planes in the package are AI.

**Comment by john681611** [comment]
There are Full AI Flights for CAP and SEAD in the options. For now, there are no mixed player and AI flights in MP mode.

**Comment by davidp57** [comment]
Easiest way to achieve this would be to generate a SP mission with AI flights, and then in the mission editor change a few aircrafts to "Client", I guess.

**Comment by john681611** [comment]
This configuration is a bit too complex for what we are going for.

But this is a really easy thing to do in the editor once the mission is generated. Just set up the Generator with MP flights with all the aircraft you want. Then go into the editor and switch any aircraft you want to be AI from client to AI type and you are good to go. 

@akaAgar  close?

**Comment by Valk77** [comment]
Sure, no problem. 

 

Van: John Harvey <notifications@github.com> 
Verzonden: zondag 7 februari 2021 12:26
Aan: akaAgar/briefing-room-for-dcs <briefing-room-for-dcs@noreply.github.com>
CC: Valk77 <jurgen.vandereviere@telenet.be>; Author <author@noreply.github.com>
Onderwerp: Re: [akaAgar/briefing-room-for-dcs] Option to add AI flights to a MP mission (#56)

 

This configuration is a bit too complex for what we are going for.

But this is a really easy thing to do in the editor once the mission is generated. Just set up the Generator with MP flights with all the aircraft you want. Then go into the editor and switch any aircraft you want to be AI from client to AI type and you are good to go.

@akaAgar <https://github.com/akaAgar>  close?
