### ISSUE TITLE
Livery issue

### ISSUE THREAD

**Issue by VCW3-admin** [akaAgar/briefing-room-for-dcs#59]
Hi. Just wanted to say this is incredible work. Thank you. 
However, I just downloaded it and tried it out with a new mission. When I go to edit the mission, I’ve noticed that you can not change the liveries in any aircraft. Example if you choose an F18 to fly all aircraft liveries in the ME will show up as the F18. Hope this makes sense and if not I can post a screen.

**Comment by john681611** [comment]
So you can't select liveries in the editor? You can select the livery in Re-arm menu when playing. Please check the county of the jet because Livers are limited by county

**Comment by akaAgar** [comment]
That's weird, as BriefingRoom uses the "Joint Task Force" coalitions, all liveries should be available to the players. But yeah, atm it always default to a basic livery. I'll may add a "random livery by country" feature later on that would select a random livery matching the unit's country but that would require LOTS of scraping (adding liveries for each countries to each aircraft's ini .file)

**Comment by PSYKO-nz** [comment]
+1 on this, on behalf of a mate, this has happed every mission we have played and the latest time was last night we did one, in the f14 me and one of my mates can change my livery no problem at all but none of my 3 mates who fly the f18 can change there liveries, no matter what the settings/options are.

I have not opened the missions in the mission editor. Just created them, loaded and played them on our dedicated server

**Comment by john681611** [comment]
I'm not convinced this is an issue of the generator. I've not had any issues with the custom liveries I have created. (F-18,F-16,M-2000C)

Joint task force is actually considered a country by ED (extract from `DCS World OpenBeta\Scripts\Database\db_countries.lua`)
```
country:add('CJTF_BLUE' ,_("Combined Joint Task Forces Blue"), "CJTF Blue", "BLUE",
  use_default_ranks,
  no_awards,
  no_squadrons
);

country:add('CJTF_RED'  ,_("Combined Joint Task Forces Red"), "CJTF Red", "RED",
  use_default_ranks,
  no_awards,
  no_squadrons
);
```
Liveries are limited to countries as part of their config in `description.lua` (M-2000C has all its Livery forced to just France for example)
```
countries = {"USA", "UK"}
```
Remove this line to allow any county
