### ISSUE TITLE
m2000c bug

### ISSUE THREAD

**Issue by bomberns127** [akaAgar/briefing-room-for-dcs#595]
### Brief Description: 
 i have created a few air to ground missions but when i go to fly them i get an error every time,it says invalid frequency 124mhz, 
i have created missions for other planes but this is the only plane that will not work

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment]
Fixed updated to 225.0 will be released in the next update thanks for the report
