### ISSUE TITLE
Persian Gulf airbase frequencies are wrong 

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#604]
### Brief Description: 
 Creating missions within Persian Gulf I’ve noticed that frequencies for the airbases are entered wrong from what’s in the sim itself. 

### Expected: 
 Forgive me but I thought the frequencies are entered into the aircraft as presented. If that’s the case no frequencies are added to client AC. 

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment]
Is this comparing the sim and the BR briefings or preset frequencies in the aircraft?

**Comment by Wood-VCW3** [comment]
Both frequencies in the aircraft and on the briefing. Sorry, I’m out of town right now and can’t check which other airports.

**Comment by john681611** [comment]
Ok then ED has changed it on us
We need compile a list of what has changed
