### ISSUE TITLE
Moose ATIS doesn't work for Syria Incirlik

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#610]
#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by HILOK** [comment]
not working on marianas either with 230108-1401.
tried with huey and hornet / with and without enabling MOOSE in options

**Comment by john681611** [comment]
> not working on marianas either with 230108-1401. tried with huey and hornet / with and without enabling MOOSE in options

I'm gonna need some example airbases for that please

**Comment by john681611** [comment]
Cause: Bad scripting link to the require ground aircraft and the ground aircraft for radio wasn't active at the start of mission
