### ISSUE TITLE
Invalid radio frequencies for some aircraft

### ISSUE THREAD

**Issue by c3f59** [akaAgar/briefing-room-for-dcs#637]
### Brief Description: 
Some aircraft get invalid radio frequencies set by BR.
Confirmed with: F-5E getting 124 MHz & Mig-15bis getting 3 MHz

### Expected: 
Frequencies should be within bounds of aircraft capabilities.

**F-5Es AN/ARC-164** accepts freqs between 225.000 and 399.975 MHz
Default presets seem to be:
![image](https://user-images.githubusercontent.com/45612174/219904427-fba0650f-f05a-459f-9b8c-556b11159866.png)

**Mig-15 Freq Table:**
![image](https://user-images.githubusercontent.com/45612174/219904329-8bcb1e66-816c-4762-8cf5-c140969ef464.png)

**Comment by john681611** [comment]
These are fairly easy updates to ini files. I'm happy to point them to you if you want to correct them yourself faster than I'll get round to it.

**Comment by c3f59** [comment]
Looks like you've been faster and did the corrections already? If not, point the way!

**Comment by john681611** [comment]
I've only done it for the AI aircraft to stop breaking missions I've not set player frequencies
