### ISSUE TITLE
Missions are generating wrong Airbase Tacan Channels 

### ISSUE THREAD

**Issue by Wood-VCW3** [akaAgar/briefing-room-for-dcs#642]
beta-release-230220-220267)  DCS Version: DCS Open Beta 2.8.2.35632

### Brief Description: 
 I've been noticing a couple of issues. 
1st. It seems that when missions are being generated they are creating Tacan channels for the airbases which are different from what DCS has. The Tacans generated by the mission do not work and you still need to use the ones defaulted in DCS.  

### Expected: 
Briefing should be listing the default DCS Tacans and not listing the ones generated from the mission 

#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by john681611** [comment]
So the TACAN channels of a flew airbases are not correct can you please log them here so I can check and correct them.
