### ISSUE TITLE
Feature TACAN Beacon Frequency in Airbases Table

### ISSUE THREAD

**Issue by Raider1-1-Boo** [akaAgar/briefing-room-for-dcs#644]
Please add the TACAN beacon frequency to the Airbases table

**Comment by john681611** [comment]
This requires core changes to DCSMissionBriefing, particularly moving from a string system to an object system for each type of briefing. Then moving from list to the dictionary. None if this is bad and allows lots of flexibility  just will be more refactoring work than actual work to add the feature.

**Comment by Raider1-1-Boo** [comment]
You asked me to leave you a reminder on GitHub.  It is not a game changer, now that I know where to look for it on the briefing, it's all good.

**Comment by john681611** [comment]
It's a dev note for me to remember what I figured out was needed. I do actually want to do this as it has advantages
