### ISSUE TITLE
Respawned Cap doesn't engage palyer or ai

### ISSUE THREAD

**Issue by Zachc123885** [akaAgar/briefing-room-for-dcs#661]
#### Mission and Template Zip: [Uploading Syria - Operation Bright Atlas.miz…]()

Mission modified: No

**Comment by john681611** [comment]
@Zachc123885 you don't seem to have uploaded a mission properly. Sometimes you have to wait a bit before submitting

**Comment by john681611** [comment]
Testing in the latest beta and it works fine.
