### ISSUE TITLE
Cannot generate campaign

### ISSUE THREAD

**Issue by shi4stone** [akaAgar/briefing-room-for-dcs#662]
Tried to create a campaign, but always gets Error: Input string was not in a correct format. when hitting generate button

This is even after reset template.

Pleae advise possible fix. thanks!

**Comment by john681611** [comment]
Can you please provide the version you are using including build number (in bracnkets)
Also is this Desktop/Website/Website running locally and have you tried the others?

**Comment by shi4stone** [comment]
this is version 221115-1711. used the desktop version, havenot tried other yet

**Comment by zbenesch** [comment]
Will do later tonight.

**Comment by zbenesch** [comment]
The beta had less problems generating the campaign.
The file \BriefingRoom\Include\Jpg\Flags\RSII.jpg is called but the name of the file is actually RSSI.jpg, renaming it to RSII.jpg solved the problem.
If more aircrafts are selected than the available parking spots are selected the generator does not finish.

**Comment by john681611** [comment]
> The beta had less problems generating the campaign. The file \BriefingRoom\Include\Jpg\Flags\RSII.jpg is called but the name of the file is actually RSSI.jpg, renaming it to RSII.jpg solved the problem. If more aircrafts are selected than the available parking spots are selected the generator does not finish.


Thanks for the info. I've corrected the image name issue thanks for the report. I've also reduced the chance for the "no parking spots" error to occur by letting the generation continue with non critical aircraft (CAP and Feature aircraft)

**Comment by zbenesch** [comment]
Nice! Keep up the good work!
