### ISSUE TITLE
Campaign mission not retaining features

### ISSUE THREAD

**Issue by ansirial** [akaAgar/briefing-room-for-dcs#664]
When generating a campaign only the first mission uses the setup, the next ones miss some settings, for instance if an airport is given it switches to random from the second mission. Also happens with other features.

**Comment by john681611** [comment]
Your settings for campaigns are a starting point. The campaign may move the airbase and change the situation as the missions progress.

**Comment by ansirial** [comment]
For instance, in the campaign setting is present the selector for the airbase, by default it's on "random", I supposed that set it up on a specific base, it will maintain the airbase during the whole campaign. At the moment sets only the base for the first mission.
I don't understand why it should work only for the first mission, it makes no difference between the "random" mode.

**Comment by john681611** [comment]
No, it's a feature that your base changes during the campaign.  The one you set is only for the initial mission. Unfortunately, most campaigns don't have logically shifting front lines but the feature works best with those few that do as it's supposed to keep you in your desired range of the action.

**Comment by ansirial** [comment]
Ok, I understand, but is it possible to retain in some manner the airbase for the whole campaign? I would like to setup a campaign not involving any moving front, this can be useful for some cases, I'm trying to recreate conditions to recreate real based operations (for instance the attrition war between Syria and Israel) where the the airbase remain the same for a whole cycle.

**Comment by john681611** [comment]
Ok I've added a "None" Option to airbase variation distance should be out in the next beta. Mission Features should also not change mission to mission

**Comment by ansirial** [comment]
So if "none" is chosen it randomize, otherwise it will retain the base right?
If so it's great! It would very useful to recreate historical routinary campaigns in some situations for instance the inherent resolve campaign.
Thanks a lot

**Comment by john681611** [comment]
![image](https://github.com/akaAgar/briefing-room-for-dcs/assets/10814889/d019aaad-a663-493a-84bf-db9815fecd76)
If set to None the airbase will not change. the higher the value the further the tool will look between missions for available airbases to jump to (Yes its also been moved to a more suitable tab).

You can also see a Static situation option here which means the situation won't change throughout the campaign

**Comment by ansirial** [comment]
Fabolous! Thanks a lot
