### ISSUE TITLE
Wrong units in ww2 40s 

### ISSUE THREAD

**Issue by Derrick006** [akaAgar/briefing-room-for-dcs#667]
Downloaded the last version of BR.

Which is excellent.
Tested it on ww2 missions on Normandy map ww2 assets clicked on Allies vs Nazi Germany

only few things to say:
- statics helo spawned on airfields
- red artillery spawn under red combined forces with a Russian self propelled artillery
- Blue artillery spawn under blue combined forces 
- With a paladin self propelled artillery 
- German bombers spawn with B17 

otherwise all good 👍

**Comment by john681611** [comment]
Thanks for the feedback. It looks like the unit selection is doing its best but can't find suitable units. I'll quickly go through the units and see if any where missed.

**Comment by john681611** [comment]
Seems there were quite a few errors in units here and a bunch missing next beta should have this setup better. 

Many AAA units are now complete sites with gun directors (they will likely fire more now)
Artillery for allies and Germany was not configured so was defaulting to modern units.
JU-88 now classified as a bomber so B17 shouldn't show up as german.

**Comment by Derrick006** [comment]
Good stuff I m sure you ll manage it. Your app is excellent anyway just easier not having to go through all the units in the mission editor to fix it 🤟

**Comment by Derrick006** [comment]
> Seems there were quite a few errors in units here and a bunch missing next beta should have this setup better.
> 
> Many AAA units are now complete sites with gun directors (they will likely fire more now) Artillery for allies and Germany was not configured so was defaulting to modern units. JU-88 now classified as a bomber so B17 shouldn't show up as german.

Excellent !!! Can’t wait

**Comment by john681611** [comment]
Now in latest beta

**Comment by john681611** [comment]
This is likely due to it defaulting back to SAM sites. I really need to implement a change to allow for unit families to not have defaults especially SAM sites in the 1940s
