### ISSUE TITLE
No radio with AWACS or tanker

### ISSUE THREAD

**Issue by steelrfan85** [akaAgar/briefing-room-for-dcs#67]
I can’t contact AWACS or the tanker even though my frequency is set.

**Comment by john681611** [comment]
Do you use easy comms usually?

**Comment by steelrfan85** [comment]
I tried both.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by john681611** [comment]
hmm, should be fixed in the next version with separated frequencies for support aircraft. But I've not had issues unless the frequency is wrong or I've got a jet that's not compatible with the tanker I'm calling

**Comment by steelrfan85** [comment]
Why can’t I go into the mission planner for my F14 missions in my campaign?  Every aircraft works but the F14 just hangs and I have to close DCS

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steelrfan85** [comment]
I tried easy comms and both radios I have binded. No joy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by john681611** [comment]
I've got the F-14 for the free period let me see if I can find the problem for you.

**Comment by john681611** [comment]
Ok I can communicate fine with both AWACS and Tankers (Note 1 tanker won't respond as it doesn't support the F-14)
I had jester doing the tuning radio manually and used the Mic press buttons to talk (F-18 has similar setup)
![image](https://user-images.githubusercontent.com/10814889/107144972-73fc5800-6936-11eb-859a-ad1a76333545.png)

@akaAgar  this can be closed as it works
