### ISSUE TITLE
Option to launch in-air

### ISSUE THREAD

**Issue by roooots** [akaAgar/briefing-room-for-dcs#672]
### Brief Description: 
Include the option to launch in-air in addition to 'on runway' and 'parked' - for example for specific training and testing scenarios.

### How does it work: 
UI: select launch type 'in-air'. In the mission it could default to coordinates of the runway, but at 5000ft, for example. Options could be added to choose both altitude and location, or make them random.

### Why can't it be done in the ME quickly: 
 I think DCS's ME supports it, but lacks many other capabilities of Briefing Room.

Thanks,
r.

**Comment by john681611** [comment]
Ok just checked this is possible in MP so we can do it but It could be a while as it kinda tears up a few things.

**Comment by roooots** [comment]
Thanks! TBH I would already be happy to see this in SP ;-)
