### ISSUE TITLE
Placing location hints - not displayed and not removable

### ISSUE THREAD

**Issue by awabom** [akaAgar/briefing-room-for-dcs#673]
### Brief Description: 
Setting 'location hint' for mission objectives does not work properly.

1. If you first add a hint, then double-click to remove.. then try to add a hint again it does not show up). But if you close the hint-window and open 'View Location Hints' the hint is sometimes there.
2. After adding two objectives and setting hints for both of them, it seems impossible to remove the hints again. Even if double-clicking removes the icons (And they stay gone even when opening locaion hints), they are used for generation.
Saving a template and reloading it shows the points again.

### Expected: 
The locations should always be displayed if they are there, and remove properly when double-clicked.

#### Mission and Template Zip: [hint_bug.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/11301792/hint_bug.zip)

Mission modified: N

**Comment by john681611** [comment]
Thanks for the report. The replacement marker wasn't being added due to the Old marker not being properly removed and a new click event being set up. The down side it's fairly hard to remove more than one marker now but the solution will be a "Clear" button to get rid of everything.
