### ISSUE TITLE
Error when request CAP support

### ISSUE THREAD

**Issue by muzica9** [akaAgar/briefing-room-for-dcs#676]
### Brief Description: 
 

Error when request CAP support

![Screenshot 2023-04-29 144751](https://user-images.githubusercontent.com/65247381/235301127-c226ebed-7582-4b83-993c-64d0906f0939.png)

### Expected: 
 

error pop-up and no Cap on designated area
#### Mission and Template Zip: 
[PersianGulf - Operation Efficient Hunt.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/11359064/PersianGulf.-.Operation.Efficient.Hunt.zip)

Mission modified: Y/N 

with build221115-1711 i have no error

**Comment by john681611** [comment]
The variable was unassigned thanks for pointing it out.
