### ISSUE TITLE
Generated Files Not Loading in Briefing Editor

### ISSUE THREAD

**Issue by mrbones1031** [akaAgar/briefing-room-for-dcs#686]
### Brief Description: 
When I try to loading any .miz file that I have generated using BR into the BR Briefing Editor, nothing appears to happen. I can load in mission files that were not created in BR into the Briefing Editor just fine and their text will appear and can be changed, so it appears to only affect missions created with BR 

### Expected: 
 I read the manual and I think I'm doing everything right, is there something that I'm missing?

#### Mission and Template Zip: 
[Briefingroom_simple_strike_test.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/11445421/Briefingroom_simple_strike_test.zip)

Mission modified: No

**Comment by john681611** [comment]
Briefing editor is now a bit redundant as I fixed ME editor functionality but I'll look into it.

**Comment by mrbones1031** [comment]
In case it helps provide you with additional info, if I open a generated mission in the ME, change the briefing, and then save it, the game will hang up in the loading screen when I try to load up the mission. Let me know if there is anything I can do to help you in regards to testing, etc.!

**Comment by mrbones1031** [comment]
Sorry I didn't mean to close it when I commented, I'm sort of new to how GitHub works. 

In case it helps provide you with additional info, if I open a generated mission in the ME, change the briefing, and then save it, the game will hang up in the loading screen when I try to load up the mission. Let me know if there is anything I can do to help you in regards to testing, etc.!

**Comment by john681611** [comment]
Fix should be in next beta
