### ISSUE TITLE
Wind is sometimes extremely high even when set to "auto" with weather set to "clear" or "lightly cloudy"

### ISSUE THREAD

**Issue by akaAgar** [akaAgar/briefing-room-for-dcs#69]
Someone raised the issue on /r/hoggit too, but didn't provide any extra info

[Operation Steady Rain.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5901024/Operation.Steady.Rain.zip)

**Comment by john681611** [comment]
This brings up another problem I have seen extreme weather where the airport is closed at the start of a mission. I'm assuming wind can be part of that.

**Comment by akaAgar** [comment]
I'm sure it's part of the same problem, yeah. I just had the same bug again while testing something in a branch (it was so windy that I had to press the wheelbrakes or my idle Su-25T would have been pushed out of the parking space), and I noticed that precipitation was set to rain and cloud cover was set to 8. But the sky LOOKED clear. So I'm pretty sure it's not that wind is set to stormy with clear sky (something that really should never happen seeing how "auto" wind is generated) but that the mission was generated with bad weater and wind, but the settings are such that the weather LOOKS good, hence the impression of a "storm with clear sky".

Anyway a possible (temporary) fix would be to set Clear weather as a default instead of Random, or to create a new "Random but pretty good" weather setting (something like the "random time but not night" we already have) that would perhaps add some random light cloud cover but never generate extreme weather.

**Comment by john681611** [comment]
Seeing this we have situations where the runway is closed on missions start.

**Comment by john681611** [comment]
Weather is set per Map which I can see the initial thinking off but considering its copy-paste between them all it seems a bit repetitive.

Also worth noting fog is coded in such a way that it's guaranteed on overcast or higher settings when it actually should be setting min visibility or max thickness. Think I'll move the weather config to a single place so we can manage it better for now.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
