### ISSUE TITLE
No F-86 Sabre

### ISSUE THREAD

**Issue by FrauSchmitt** [akaAgar/briefing-room-for-dcs#70]
Hi,
I just wanted to create a mission in the 1950', but it seems, that the F-86 Sabre is not included ;)

**Comment by akaAgar** [comment]
Looks like I forgot it. Fixed it, it will be included in the next release.

In the meantime, if you want to fly it, edit "Database\Units\PlaneFighter\F-86F Sabre.ini" and set "PlayerControllable" to "True"

**Comment by FrauSchmitt** [comment]
Thx!!

**Comment by john681611** [comment]
Fixed in for release
