### ISSUE TITLE
Option to set Starting Airfield in "Campaign" mode

### ISSUE THREAD

**Issue by sncollie** [akaAgar/briefing-room-for-dcs#71]
Love the Campaign Beta...I like the "randomness" of the missions.  However, I was hoping for the option to choose your airfield...like the single mission generator has.  I understand this is Beta, so forgive me if this is already in the works.  Love the program (and your previous Headquarters)

**Comment by akaAgar** [comment]
That's a good idea, I'll add it in the next version.

**Comment by akaAgar** [comment]
Done, will be available in next release
