### ISSUE TITLE
Missing plane: Bf 109 K-4

### ISSUE THREAD

**Issue by JussiFIN** [akaAgar/briefing-room-for-dcs#72]
I found this tool today, flew whole evening and its great! However I couldn't find my favorite plane Bf 109 from it. Is it possible to add?

**Comment by FrauSchmitt** [comment]
I think, it's similar to this missing Sabre. Maybe this workaround may help too ;)

https://github.com/akaAgar/briefing-room-for-dcs/issues/70

**Comment by JussiFIN** [comment]
Thanks! It shows up on the list now.

**Comment by john681611** [comment]
Fixed in for release
