### ISSUE TITLE
Closest objective distance is 60km?

### ISSUE THREAD

**Issue by JussiFIN** [akaAgar/briefing-room-for-dcs#73]
Objective distance on closest setting seems to be about 60km. That's probably a blink of an eye for F-18, but for UH-1H copter or WW2 airplanes that's much longer. I was wondering if there could be even closer setting for that? Something like 30km?

Anyway, what a great program this is! I have been flying all evening since this finally makes possible to generate WW2 fights.

**Comment by JussiFIN** [comment]
Somehow with my amateur skills I succesfully cloned the repo and changed _VeryLow_ and _Low_ distances in _Objectives.ini_. After testing _VeryLow_ distance it works much better for short 15-30 minute missions for 1940's WW2 era airplanes.

I think many WW2 era players will like this change, so I try to make my first ever pull request.

**Comment by akaAgar** [comment]
"Objective distance" is now an integer, so users are free to set the objective distance to their liking. Should fix the issue for any period and type of aircraft
