### ISSUE TITLE
Add Pucara Mod

### ISSUE THREAD

**Issue by Montykoro** [akaAgar/briefing-room-for-dcs#751]
### Brief Description: 
Include PUCARA MOD 
### How does it work: 
For the SA is basic to have the A4 and the Pucara. 

Info About the mod:
https://github.com/PucaraPastrana/PucaraDCS

Thanks!

**Comment by john681611** [comment]
Q: This mod seems dead since 2021. I assume it still works on the current DCS OpenBeta?
Reading the the forums a bit it's also got a work-stealing issue against it. I'm uncomfortable with adding the mod if that is still the case. If you can link me any evidence that it's been resolved (confirmed by the person complaining) that would make me feel better.

**Comment by Montykoro** [comment]
Hi, nice to meet you John, thanks for the time and dedication on BR!

The Pucara dev (Pastrana) is on our clan, so we gonna talk about this on the next meeting.

Thanks again and have a good one!




El 19 sep. 2023, a la(s) 06:55, John Harvey ***@***.***> escribió:

﻿

Q: This mod seems dead since 2021. I assume it still works on the current DCS OpenBeta?
Reading the the forums a bit it's also got a work-stealing issue against it. I'm uncomfortable with adding the mod if that is still the case. If you can link me any evidence that it's been resolved (confirmed by the person complaining) that would make me feel better.

**Comment by Montykoro** [comment]
Hi, yesterday talk to Pastrana and the mod will be updated but not on the short time.

On the topic about the complaint is too much hazle to provide evidence to support or not the claims from the other guy, if the subject cause controversy from you for “support a work-stealing issue “ please close the ticket and thanks for your time.

Have a nice day and again thanks for your time.



El 19 sept 2023, a la(s) 09:34, Damian Caerols ***@***.***> escribió:

﻿ Hi, nice to meet you John, thanks for the time and dedication on BR!

The Pucara dev (Pastrana) is on our clan, so we gonna talk about this on the next meeting.

Thanks again and have a good one!




El 19 sep. 2023, a la(s) 06:55, John Harvey ***@***.***> escribió:

﻿

Q: This mod seems dead since 2021. I assume it still works on the current DCS OpenBeta?
Reading the the forums a bit it's also got a work-stealing issue against it. I'm uncomfortable with adding the mod if that is still the case. If you can link me any evidence that it's been resolved (confirmed by the person complaining) that would make me feel better.

**Comment by Montykoro** [comment]
Thanks!

**Comment by Montykoro** [comment]
.
