### ISSUE TITLE
The ability to import loadouts from a loadout manager...

### ISSUE THREAD

**Issue by gkleinfe** [akaAgar/briefing-room-for-dcs#752]
### Brief Description: 
More convenience with regards to creating and using custom loadouts loadouts would be nice.

### How does it work: 
There already is a web based loadout manager (https://dcsworld.pro/loadouts) that allows the exports of a custom loadout.  Have the ability to import the lua file that is exported from this site into Briefing Room.

Or, create your own loadout manager that then can be imported the same way.

Or, be able to import any game generated LUA loadout information into the app.

### Why can't it be done in the ME quickly: 
Adding a custom loadout, currently, is quite confusing.  I'm struggling to follow the documentation.  I did it before, but I'm not sure if I'm not following the documentation quite right or if it's outdated, but I'm not having any luck doing it.

**Comment by john681611** [comment]
If you run the tool locally then any loadout you have in the game should be usable

**Comment by john681611** [comment]
I'm closing this as we won't be supporting this any time soon.
