### ISSUE TITLE
Enemy targets inside friendly territory

### ISSUE THREAD

**Issue by ansirial** [akaAgar/briefing-room-for-dcs#760]
### Brief Description: 
When generating a campaign in some missions targets are inside friendly territories or neutral territories, structures too

### Expected: 
I expect targets are only inside enemy territory

#### Mission and Template Zip: 
[Syria - Operation Unrelenting Clay.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/12898169/Syria.-.Operation.Unrelenting.Clay.zip)
See mission 2, 6, 8, 9, 10
Please also note this is generated from a custom situation, also included in the zip

Mission modified: N

**Comment by john681611** [comment]
Spawning logic is rather complex. Priority should be.
1. Anywhere it will fit (objectives only)
1. Not in No Spawn zones
1. Relative to the front line (yes units can be behind enemy lines how far depends on the unit)
1. Not in hostile border

Basically yes AI can spawn on the hostile side to represent recon or surrounded units.  This most often happens in areas of relatively low spawn point density (a manual task) where the tool is forced to make do.
If you can share some screen shots that would help me look at any particularly nuts ones.

**Comment by ansirial** [comment]
Sure, here few screens:
![Screenshot 2023-10-15 184112](https://github.com/akaAgar/briefing-room-for-dcs/assets/84128920/ceb3b43b-3cdc-4d09-b486-63c8c27e4efe)
![Screenshot 2023-10-15 184159](https://github.com/akaAgar/briefing-room-for-dcs/assets/84128920/c521fbe9-036d-4ed1-a43a-803b44f1c786)
![Screenshot 2023-10-15 184248](https://github.com/akaAgar/briefing-room-for-dcs/assets/84128920/0c4162b2-24b0-45f4-9ee0-39d642d8fae8)

Understood but a whole surrounded enemy structure (or a tracking radar) in the deep of friendly territory is quite strange :)
Also happens enemies are placed outside the boundaries of the map, especially for planes but not exclusively.
Can be related to the "Static Situation" option?

**Comment by john681611** [comment]
Can you turn on the other map options to show front line and units

**Comment by ansirial** [comment]
Sure, here you are:
![Screenshot 2023-10-15 210631](https://github.com/akaAgar/briefing-room-for-dcs/assets/84128920/79e2063e-f0f4-436d-b180-653ebe9fedb1)
Static situation off, seventh mission out of ten, with the frontline seems have sense.
Is it intended to work so?

**Comment by john681611** [comment]
Hmm it is definitely placing objectives in the blue zone I'll look into it and see if there is a positioning bug

**Comment by john681611** [comment]
Ok I've found the cause and its specifically campaign missions affected. Basically between missions the objective center point is used as a hint for the next mission. This is so you don't fight in wildly different areas each time. This hint ignores borders to get most accuracy.  I think it probably should not and you need SpawnAnywhere turned on for it to work. 

 Fix will be out in next beta
