### ISSUE TITLE
Add combined joint task force blue and red to coalitions list

### ISSUE THREAD

**Issue by crackmolon64** [akaAgar/briefing-room-for-dcs#772]
### Brief Description: 
adding the cjtf blue and red factions to the list of coalitions to the software would really help with developing fictional scenarios and filling in for missing units ED hasn't added or wont add to some of the factions currently present in the generator through the full mission/campaign generator

### How does it work: 
 could be the same as the other coalitions

### Why can't it be done in the ME quickly: 
it'd remove a lot of the point of using the  mission/campaign generators if i had to go through every mission adding and editing every unit by hand, at that point i could just make the missions myself

**Comment by john681611** [comment]
Combined joint task force blue/red are default factions on either side.
What units go on what side is defined here: https://github.com/john681611/dcs-data-miner/blob/main/customDataSets/UnitOperators.json I don't think cjtf sides are used in that list but it may not be a bad idea for more generic units like infantry ect
