### ISSUE TITLE
CAS Mission Crash on Nevada

### ISSUE THREAD

**Issue by atSurvival** [akaAgar/briefing-room-for-dcs#80]
Would fly a short CAS Mission on NTTR but game is crashing when I hit the "fly" Button..
I have tried different Enemy units but allways the same.
Flew Yesterday 2-3 Missions in Syria and all was fine.

[Briefing Room.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5958808/Briefing.Room.zip)

**Comment by atSurvival** [comment]
EDIT: The same settings in Syria all is working.
[Briefing Room2_Syria.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/5958842/Briefing.Room2_Syria.zip)

**Comment by BlackRookSix** [comment]
Cannot launch any .miz based in Nevada, as well.

**Comment by Grom991** [comment]
The same thing for me : crash of the game when I hit "fly" button. Only with Nevada map...
For your information, with no playable plane there is no crash.
Please correct it. 
Many many thanks in advance.

**Comment by stevie02** [comment]
Yep, me too. With Viper it won’t get past loading when I select ‘fly’. Harrier makes it that far but game won’t recognise throttle. All other maps I have are fine. Just Nevada.

**Comment by john681611** [comment]
Ok looks like Nevada is bugged. As I don't personally have the map I'm gonna need some help on this please make a shout out on our discord testing chat and I'll see if we can work together on fixing this.

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
