### ISSUE TITLE
S-300's big bird search radar doesn't activate during DEAD missions 

### ISSUE THREAD

**Issue by MrWheatleyy** [akaAgar/briefing-room-for-dcs#802]
### Brief Description: 
S-300 doesn't engage cause the search radar is off 

### Expected: 
The Search Radar should turn on and allow the site to engage aircraft 

Mission modified: No

**Comment by john681611** [comment]
Can you share an unmodified mission with this issue? 
Are you using Skynet IADS?
Is this a Modded unit?

**Comment by MrWheatleyy** [comment]
unmodded and no iads
[mission.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/13721064/mission.zip)


> Can you share an unmodified mission with this issue? Are you using Skynet IADS? Is this a Modded unit? Please also test with the latest beta

**Comment by john681611** [comment]
Ok confirmed the SA-10 site is functionally dead it won't launch against me. The template does look wrong though so I'll test with default SA-10 templates and look at checking the data.

**Comment by john681611** [comment]
Ok, Fixed template shuffleing but I'm still seeing a buggy SA-10 site spawn so trying to figure that one out.

**Comment by john681611** [comment]
Found the buggy templates they where old manual ones of mine. I've now added the new ED ones and made some SA-10 Variants with different radars
