### ISSUE TITLE
Enhancement: Add options to control how many ground units are generated

### ISSUE THREAD

**Issue by jkaryan** [akaAgar/briefing-room-for-dcs#82]
Just thought I'd add this here:

### "Issue:"
There doesn't seem to be a way to set how many non-anti-air ground units should be spawned.
You can set the skill level of the ground units, and the "intensity and quality" of the air defenses, but can't for example force a large number of tanks, IFVs, APCs and infantry to spawn.

###  Solution:
Add selections for the intensity and number of ground units, possibly also what type (Heavy Armor, Light Armor, Soft, Infantry, Random) to focus on. This would make generating CAS missions significantly better.

As an example, we just generated a CAS mission for two A-10C II's, and flew some 120 nautical miles to blow up two T-55s. This was a little underwhelming, and we can't see a way to force the number to be higher without manual editing (which ruins the surprise).

**Comment by john681611** [comment]
2 Short term options
1. More Objectives say 4-5
2. Modify objective config in Database/Objectives/Close air support.ini and increase the count min max under unit group

**Comment by john681611** [comment]
> Objetive Count should not control both number of objetives ( waypoints ) and number of targets because it is very difficult to predict how many bombs or missiles you should carry or how many wingmans
> There should be 2 different config options for that:
> Nº of Strike Locations: Number of strike locations ( waypoints ) that will available on the mission
> Nº of Targets: Number of targets to destroy that will be on each objetive ( random number with min/max defined by the player ) ( 2-6 )

From #139  @SpartanEsp

**Comment by john681611** [comment]
Current thinking is a briefing to give an estimate of numbers  (right from the objective config) add a multiplier that goes from something like  .25 - 5x to increase or decrease the number of targets. This solution leaves the randomness that you would have IRL from fuzzy intel but allows you to generally scale for your expected number of players.

**Comment by john681611** [comment]
Done to a point in 0.5
