### ISSUE TITLE
Error: Mission could not be generated: Spawning on airbase is not a valid Sub Objective

### ISSUE THREAD

**Issue by Sandwich2001** [akaAgar/briefing-room-for-dcs#845]
### Brief Description: 
 When using the "full" generator - adding a few aircraft, an error appears during compilation:
 "Error: Mission could not be generated: Spawning on airbase is not a valid Sub Objective unless main objective is also spawning on airbase.
 
Couldn't find anything in the DOCS explaining why this happens. Nor any previous issues with/without fix to this issue.

### Expected: 
Not sure, would've liked some document guidance on this error. Otherwise would've thought it'd compile- But likely user-error

Mission modified: N

**Comment by john681611** [comment]
As it says you are trying to have a sub-objective that requires spawning on an airbase. This can only happen if the main (first objective in the set is also on an airbase) this is simply due to how the spawning logic works.

Maybe better wording is needed to describe a "Main objective" but its the first one on that tab.

**Comment by Sandwich2001** [comment]
I figured it is a problem with what exactly it saying is wrong... but i have no idea what is causing it, and what to change to make it work so far.
Again, i get it - sometrhing with a sub-mission, but which one? and is there documentation on how to make it work in a way that Briefing Room is designed to?

Thanks for the swift reply!

**Comment by john681611** [comment]
If you share the template then I can help you determine which one is at fault.  But the tool can't tell you much without the error message becoming more complex

**Comment by Sandwich2001** [comment]
[github - mission template folder.zip](https://github.com/akaAgar/briefing-room-for-dcs/files/14225770/github.-.mission.template.folder.zip)


Sorry, thought it already added this! whoops

**Comment by john681611** [comment]
Your cause and a newer error message to come with better indication of "Base" and "Nearby" Objective types
![image](https://github.com/akaAgar/briefing-room-for-dcs/assets/10814889/4ab6f85b-4917-45cc-913d-3cb65e70f19b)
