### ISSUE TITLE
Enable ground units once player is in area

### ISSUE THREAD

**Issue by spooky386** [akaAgar/briefing-room-for-dcs#859]
### Brief Description: 
 Enable ground units when player is in zone

### How does it work: 
 once the player is in the mission zone, the enemy and friendly ground AI will become active, at the moment they start combat as soon as the player starts the mission, so by the time the player arrives on the front line, the battle has already ended. Perhaps an F10 command to announce you are on station, which will trigger the ground battle nearby

### Why can't it be done in the ME quickly: 
 although this can be created via a trigger zone, it means looking at the mission file which means the player will see where the units are, removing the element of surprise to the mission

**Comment by john681611** [comment]
So this kinda exists in a few forms:

1. Some objectives like Assault are radio triggered starts (I think defense is proximity triggered)
2. Progression options hide and disable units until the previous objective was completed.
