### ISSUE TITLE
Ability to build coop escort mission

### ISSUE THREAD

**Issue by NiJeTi** [akaAgar/briefing-room-for-dcs#873]
### Brief Description: 
Ability to set one player group to escort another in their mission

### How does it work: 
In dropdown selector of the target of the escort mission add an option with another player group.

### Why can't it be done in the ME quickly: 
It can. But will be a nice-to-have feature (with waypoints sharing and datalink support).

**Comment by john681611** [comment]
While this is technically possible I think you can happily role-play this without the need for BR code.
