### ISSUE TITLE
Enemy aircraft spawned at CAP objective point do not engage the player

### ISSUE THREAD

**Issue by Razbari** [akaAgar/briefing-room-for-dcs#89]
I've tested a bunch of CAP mission objectives, and every time the AI planes spawned at the objective point just fly their orbit around the waypoint and will never engage the player. I don't believe this is intended behavior. I haven't inspected the mission files, but there might be a missing or broken trigger.

[Here's a demonstration video](https://youtu.be/HOTEH7hmrX8?t=770)

**Comment by john681611** [comment]
Should be fixed now
