### ISSUE TITLE
Recon Objectives don't complete and have no F10 status

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#9]
Gave this a try last night the F10 status never came up and we had no info about completing objectives
Our example mission has a server error
![image](https://user-images.githubusercontent.com/10814889/103095008-00f18900-45f7-11eb-9d7c-b60418b1288c.png)

**Comment by akaAgar** [comment]
Yeah, that's no surprise, I'm away from home for the holidays so I haven't been able to test the new Lua scripts, so there's bound to be a few bugs in them. As soon as I get back home I will test and fix them before pushing the next release.
