### ISSUE TITLE
Better Target descriptions

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#90]
Hey guys, me and my mates have been absolutely loving this program, and are continuing to play at least one mission a week, some times more. We have a few notes for you, 

the first one is that it would be great if in the deep strike (and any mission where a structure is the target) it would be great if there was a better description in the briefing of the target,

Last night we did a deep strike mission amd hit 2 “structures” we were over the target area for 15-20 minutes trying to figure out exactly what “structure” the target was, until we took a look at the map to see a FARP fuel depot and a FARP ammo dump, it would have been awesome if we could have had that in the description rather than “structure”

the we wouldn’t have to go cheat and look at the map

keep up the amazing work, you guys are awesome and making me and my mates very happy with this program

Keep being awesome

**Comment by john681611** [comment]
I don't fully understand the randomisation logic for the descriptions. If you feel you are a better description writer and can get your head around how it works, Feel free to contribute improvements.

**Comment by PSYKO-nz** [comment]
I was more meaning a simple change to the descriptions basically instead of saying “a structure” as it currently does maybe just what the target is, “a fuel dump” “a ammo dump” etc, I’m not a great writer or coder but I can try take look if that is of help to you

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
