### ISSUE TITLE
Markers on map at waypoints

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#91]
Is it possible to get map markers on the map at the points of all the waypoints?

it’s tough to plan a mission (during load and taxi etc) when there are no markers on the map, we have them in our navigation computers but not on the map for us to see.

It would also let us see what waypoint was what, especially when flying aircraft like the tomcat that only get numbers or jets with no waypoint navigation system 

Also, it would be a massive help when doing CSAR or other helicopter missions to know where to go because the Huey has no navigation system, at the moment I get our f18 pilots to put a mark on the map where there computer says it is

**Comment by john681611** [comment]
Tbh this is a general DCS issue. If you have an AI wingman you can see the course on the map. The mission planner also shows you waypoints.

We may add something in future.

**Comment by PSYKO-nz** [comment]
I’ll do some checking for waypoints in multi player and get back to you, at this stage I don’t think there’s anyway to see them on map but I could be wrong, I normally am haha, I’ll check and see what I can see

**Comment by akaAgar** [comment]
Adding map markers on waypoint is easy though, I'll add it as an option

**Comment by PSYKO-nz** [comment]
Awesome, thank you, it will be super helpful, especially when playing in multiplayer and you don’t get to see the ai wingman tracks!

**Comment by john681611** [comment]
I'm working on this now just got to get the markers x-axis working.

**Comment by john681611** [comment]
done
