### ISSUE TITLE
Aircrafts are not respawning...

### ISSUE THREAD

**Issue by cbflex** [akaAgar/briefing-room-for-dcs#916]
### Brief Description: 
I setup the mission so that the aircraft would respawn, and they don't. The mission ends as soon as all enemy aircraft die.

### Expected: 
Endless Dogfights...

#### Mission and Template Zip: <!-- Drag and drop a zip of your template (.brt) file and an example mission file (.miz) here. So we can debug-
[Missions.zip](https://github.com/user-attachments/files/15522907/Missions.zip)
->

Mission modified: Y/N   Y. In the lua file, I changed the spawnchance to 9, and the interval to 120,600.

**Comment by john681611** [comment]
I've managed to watch at least one group respawn. Note the entire group needs to die for it to respawn

**Comment by cbflex** [comment]
I killed all the other planes... the only planes left were 2 allied planes.

There were zero enemy planes left...
So why do they stop respawning?

**Comment by john681611** [comment]
Let me get this straight as unfortunately its not easy to reproduce in a short amount of time.

So you are seeing flights respawn and then at some point they just stop respawning?
Or 
Are they just never respawning at all?

**Comment by cbflex** [comment]
Exactly.
I think i fixed it by increasing the spawnchance to 10 and the interval to
15,30...

**Comment by cbflex** [comment]
I think i wasnt waiting long enough

**Comment by john681611** [comment]
Yeah by default its set to more to a long-running server where people come in and out

**Comment by john681611** [comment]
I'm going to provisionally close this as it may be slow but its working
