### ISSUE TITLE
CSAR pick up is a tank?

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#93]
We’ve done 4 CSAR missions, on all for time we were heading in in hueys to pick up Keith (Keith just keeps getting shit down and we have to go get him!) on all 4 occasions Keith has been a tank, the trigger seems to work fine (altho just flying low and slow near Keith the tank seems to trigger it) but it’s a bit weird doing CSAR to rescue a pilot in a tank :)

I’m sure the tank is just a place holder or something but I thought I should bring it up just incase

**Comment by akaAgar** [comment]
Weird. That's a bug. Should be a soldier. Which country/coalition were you flying as, and during which decade? Maybe it doesn't have any infantry in the database and so it defaulted to a tank.

**Comment by PSYKO-nz** [comment]
Flying as standard blue what ever the standard blufor American nato setting is, Years between 1980 and 2000s

**Comment by john681611** [comment]
Closing as this is pre 0.5 cleanup if you still see this post 0.5 please re-open with a post 0.5 mission and template.
