### ISSUE TITLE
CSAR survivor locator beacon?

### ISSUE THREAD

**Issue by PSYKO-nz** [akaAgar/briefing-room-for-dcs#94]
Sorry to spam so many things in one go, we have been making notes and it just seemed the way to do it, 
Last one, I promise 

are we able to have the pilot we are rescuing have the option for them have a beacon we can use to navigate to them? 

Make it a bit easier for navigation in the hueys to be able to home in on a signal

Thanks again for all your work, we love this program it has changed our game notes for the better. We really appreciate it guys :)

**Comment by akaAgar** [comment]
Oh that's a good idea, I'll see if I can add it in a future version

**Comment by john681611** [comment]
@akaAgar  this exist now?
