### ISSUE TITLE
Save to local storage

### ISSUE THREAD

**Issue by WirtsLegs** [akaAgar/briefing-room-for-dcs#992]
### Brief Description: 
Would like the ability to write the mission to a mounted volume/directory in the web version

### How does it work: 
Generate a mission as per usual then where you would normally click to download the mission add a option to save to server or w/e (name it however), this would then save the miz file to a mounted directory instead of downloading it to the user's PC (to be clear suggesting adding this along with the download option not replacing the download option).

### Why can't it be done in the ME quickly: 
Not really a mission editor related feature, but this would save time overall in some cases, for example our group has a bunch of servers we use for hosting content, they pull missions from a network share that certain people have access to. This would allow us to have users easily generate missions and with 1 click deploy them to the server to be run, instead of having to download the mission then upload it assuming they even have write access tot he mission drive.

I'm not sure if other groups work similarly or not, but if so this would be a really valuable addition

**Comment by john681611** [comment]
While I can see the benefit for people using servers. I'm not sure it's possible without adding a ton of technical complexity for a niche use case.

Our group's solution is to just Remote desktop onto our server and use the installed version there or the website. (or we just transfer missions from our PCs)

I'm not sure if its allowed but when running locally you should get (unless it runs super slow) a selection window and you can try saving directly that way.

**Comment by WirtsLegs** [comment]
> While I can see the benefit for people using servers. I'm not sure it's possible without adding a ton of technical complexity for a niche use case.
> 
> Our group's solution is to just Remote desktop onto our server and use the installed version there or the website. (or we just transfer missions from our PCs)
> 
> I'm not sure if its allowed but when running locally you should get (unless it runs super slow) a selection window and you can try saving directly that way.

yeah thats fair, i made the request on principal without really digging in to how briefing room works (im a backend and server software guy not a web guy at all), if there was already some kind of backend component i figured it wouldn't be a huge ask, but if its just run 'in browser' as a webapp then yeah that's a bit much

Could I propose another option? have a option to push it to a remote server directly via ftp or upload to a gdrive folder?

**Comment by john681611** [comment]
I don't want to make external connections if I can avoid it so FTP is out. No idea how you would push to Gdrive
