### ISSUE TITLE
Save the data that is currently in the *.brt to local storage

### ISSUE THREAD

**Issue by rbz518** [akaAgar/briefing-room-for-dcs#997]
### Brief Description: 
 
Save the data that is currently in the *.brt to local storage so that it is only necessary to (clear/alter/backup/restore settings)

### How does it work: 
 
I believe this shouldn't be too difficult to put in place and won't require any server-side resources. Save the *.brt data in JSON format to the browser's local storage and add button to clear settings.

### Why can't it be done in the ME quickly: 
 

When needing to load the settings the process is streamlined to just altering previous settings.

**Comment by john681611** [comment]
Turns out its surprisingly easy to implement
![image](https://github.com/user-attachments/assets/3891ac18-be68-4750-a847-ad5d0461872f)
Its toggled by this new icon
